### ISSUE TITLE
todomvc does not destroy last item to be destroyed in list

### ISSUE THREAD

**Issue by omac777** [David-OConnor/seed#1]
Excellent work! The responsiveness of launching it directly through firefox was good.

the quick start works with one hiccup.  no pkg dir.  "mkdir pkg" fixes the issue.

I tried the todomvc example.  added four items task1, task2, task3, task4, checked them off as completed, then clicked the "X" button at the far right of each item row. task1 deleted when I clicked task1, but task3 was deleted when I clicked task2. When I clicked clear completed, it did not destroy task2 either.

**Comment by David-OConnor** [comment]
This is a bug in the virtual DOM's patching system. I'm suspicious it has to do with events(Listeners) not updating during a patch, eg the "click" trigger is remaining associated with a web_sys element from the prev version of the DOM. Would love to get this fixed in the next few days.

**Comment by David-OConnor** [comment]
Fixed; uploaded as v0.1.4
