### ISSUE TITLE
seed-rs.org has invalid TLS cert.

### ISSUE THREAD

**Issue by thedodd** [David-OConnor/seed#10]
Hopefully I didn't just stumble onto this project while you were updating the certs or doing some sort of maintenance. Either way, figured I would log an issue.

<img width="1138" alt="screen shot 2018-12-18 at 7 56 45 pm" src="https://user-images.githubusercontent.com/2380740/50194158-3e7ff500-02ff-11e9-8bc1-ace5dcc363af.png">

**Comment by David-OConnor** [comment]
Problem: Github pages doesn't support routing. Switched to Surge, which evidently doesn't support SSL on their free plan. Hopefully will be fixed by switching to Firebase

**Comment by coder543** [comment]
Netlify might also be a useful option

**Comment by David-OConnor** [comment]
Sorted, via Netlify
