### ISSUE TITLE
Proposal: Mounting

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#102]
## Suggested Changes

**1)** New possible **`.mount(..)`** calls:

```rust
// A - HTMLElement argument
seed::App::build(Model::default(), update, view).mount(seed::body())

// B - &str argument
...mount("app")  // mount to element with `id` 'app'

// C - Element argument
....mount(seed::body().querySelector("section").unwrap().unwrap())

// D - Default mount point
seed::App::build(Model::default(), update, view) // not called => same as B
```

**2)**
Remove function **`.mount_el(..)`**

## Why

- One mount function per type (`mount(&str)`, `mount_el(Element)`, ..):
  - It's not very flexible for supporting more types in the future
  - It makes codebase/API a little bit more complicated
  - We have to write `mount_el(seed::body().into())` if we want to pass `HTMLElement` as argument or implement another function like `mount_html_el`

## Resolving Breaking Changes

Removing function **`.mount_el(..)`**:

- We can mark it `deprecated` and remove it in the future
- It's missing in guide (https://seed-rs.org/guide/2), so no changes are necessary in docs

## Possible Implementation

```rust
pub fn mount(mut self, mount_point: impl MountPoint) -> Self {
    ...
}
```

## Next Steps

I'll implement it after we agree on a scope of changes. Thanks for opinions and counter-arguments.

**Comment by David-OConnor** [comment]
As usual, I have little to add: Agree on all counts - this is a syntax improvement with no obvious downsides.
