### ISSUE TITLE
Proposal: AnimationFrame

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#103]
## Suggested Changes

- Sync render loop with `requestAnimationFrame`
- Add variant `ForceRender` (or `RenderNow` (?)) into enum `ShouldRender`
  - `ForceRender` ignores `requestAnimationFrame` and forces app render

## Why

Main reason is performance, however there are some other reasons, see [dev.opera.com/articles/better-performance-with-requestanimationframe/](https://dev.opera.com/articles/better-performance-with-requestanimationframe/).

Frameworks which already use rAF:

- [Rust framework Sauron](https://github.com/ivanceras/sauron)
- Yew has it on its roadmap ([yew/issues/149](https://github.com/DenisKolodin/yew/issues/149)) and has it implemented as a [Render service](https://github.com/DenisKolodin/yew/blob/master/src/services/render.rs) (I was using it with "hacked" Yew's update function and app seems to be more responsive and animations (dragging / resizing) smoother)
- Elm
- React
- ...

## Resolving Breaking Changes

There are no API breaking changes, but there can be some special cases where `ForceRender` should be called instead of `Render`.
See [github.com/elm/virtual-dom/issues/107](https://github.com/elm/virtual-dom/issues/107) (there are broken links, just replace `elm-lang` with `elm` in their urls)

## Possible Implementation

Can be inspired by:

- [wasm-bindgen example](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/request-animation-frame)
- [Sauron's render loop](https://github.com/ivanceras/sauron/blob/f124ee6bd926e438520bc60b149b6b4d44617bbb/src/program.rs)
- [Dodrio's render loop](https://github.com/fitzgen/dodrio/blob/master/src/vdom.rs)
- [Yew render service](https://github.com/DenisKolodin/yew/blob/master/src/services/render.rs)

## Next Steps

I'll try to implement it after we agree on a scope of changes. Thanks for opinions and counter-arguments.

## Future Work

We can add hooks/events for animation frame - see [Elm-Browser-Animation docs](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Events#onAnimationFrame). It will allow us to create precise animations.

**Comment by David-OConnor** [comment]
I'm on board with this. Don't understand it ATM, but those examples look like a good starting point.

**Comment by MartinKavik** [comment]
Ok, thanks, I'll try to create some prototype and example.

**Comment by David-OConnor** [comment]
It seems like this would be accomplished by wrapping
```rust
(self.cfg.update)(message, &mut self.data.model.borrow_mut(), &mut orders);
```
in vdom's `App::update` method, but I'm battling an army of closure and lifetime-related errors.

**Comment by MartinKavik** [comment]
I'm working on it. Could you push branch with your changes for inspiration?

**Comment by David-OConnor** [comment]
https://github.com/David-OConnor/seed/blob/req_anim_frame/src/vdom.rs#L396
