### ISSUE TITLE
Proposal: Return Render implicitly

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#106]
## Suggested Changes

Return type:

```rust
fn update(msg: Msg, model: &mut Model) -> impl Updater<Msg> {
    ...
}
```

## Why

Before:

```rust
fn update(msg: Msg, model: &mut Model) -> Update<Msg> {
    match msg {
        Msg::Increment => {
            model.count += 1;
            Render.into()
        }
        Msg::Decrement => { 
            model.count -= 1;
            Render.into()
        }
        Msg::Log(something) => {
            log!(something);
            Skip.into()
        }
    }    
}
```

After:

```rust
fn update(msg: Msg, model: &mut Model) -> impl Updater<Msg> {
    match msg {
        Msg::Increment => model.count += 1,
        Msg::Decrement => model.count -= 1,
        Msg::Log(something) => {
            log!(something);
            Skip
        }
    }
}
```

- implicitly return `Render`
- no need to write `.into()`
- it would be easier to see "special" cases like `Skip` and `ForceRender` in source code
- less boilerplate code
- it would be a little bit easier for beginners to start working with Seed

## Resolving Breaking Changes

No breaking changes.

## Possible Implementation

Implement trait `Updater` for enum `ShouldRender`, struct `Update` and unit `()`. Unit will be de facto alias for `Render`.

## Next Steps

I'll try to implement it after we agree on a scope of changes. Thanks for opinions and counter-arguments.

**Comment by David-OConnor** [comment]
Agree, with no changes: A non-breaking API improvement.

**Comment by David-OConnor** [comment]
Added with updated examples and readme in latest commit. Imitated your `ElContainer` style - would never have figured it out otherwise.

**Comment by David-OConnor** [comment]
Note that all match arms appear to have to have the same type, complicating things when some arms return an `Update` (eg when fetching data), and others return `ShouldRender`.

**Comment by MartinKavik** [comment]
Yeah, I've come to the same conclusions, so I threw away my Updater version (it was implemented in the same way like your one).

So I dove deeper into `Update` API and tried to design a more consistent/simpler one. I'll create PR after this comment with my "experiment".

Well, if you look to the new example (`/examples/orders/src/lib.rs`) in that PR, you'll find this:

```rust
fn update(msg: Msg, model: &mut Model, orders: &mut Orders<Msg>) {
    match msg {
        Msg::Greet => {
            model.greet_clicked = true;
            orders
                .skip()
                .send_msg(Msg::WriteHello)
                .send_msg(Msg::WriteName("World".into()))
                .perform_cmd(write_exclamation_marks_after_delay())
                .perform_cmd(write_emoticon_after_delay(":)".into()));
        }
        Msg::WriteHello => model.title.push_str("Hello "),
        Msg::WriteName(name) => model.title.push_str(&name),
        Msg::WriteExclamationMarks => model.title.push_str("!!! "),
        Msg::WriteEmoticon(emoticon) => model.title.push_str(&emoticon),
        Msg::TimeoutError => {
            log!("Timeout failed!");
            orders.skip();
        }
    }
}
```
### Terminology
- **orders** are your requests to the "Seed runtime", which will be resolved after model update.
- Implemented **orders**: 
  - _render_
  - _skip_
  - _send_msg_
  - _perform_cmd_
- **effects** are side-effects created during model update, we can divide it into 2 groups:
   - synchronous = **messages** - _send_msg_ just calls `update` function.
   - asynchronous = **commands** - _perform_cmd_ schedules given future to be executed and once it's resolved, function `update` will be called.  

### How it works
- New struct `orders` is created in "Seed runtime" just before calling user's `update` function.  
- If you don't modify `orders` in your `update`'s body, it "contains" only **order** _render_. 
- `Orders` implements builder pattern, so you can chain your **orders** as you wish - **effects** will be created in the same sequence.
- All effects are processed in the loop (Rust can't do tail call elimination, so recursion it's not possible and it would also blow JS call stack). 
- Calling `.perform_cmd` more times is the alternative to the Elm's [Cmd.batch](https://package.elm-lang.org/packages/elm/core/latest/Platform-Cmd#batch).
- We have more freedom with Rust and futures than in Elm so I think that special `map`, `and_then` , etc. for mapping effects are not needed (can be added later).

### Resolving breaking changes
Yeah, it's pretty big breaking change, but I think that it will bring more features, flexibility and consistency into Seed's API.
Also it would be easier for beginners to learn Seed - you don't have to learn what is `Update<Msg>`, `Render`, `Skip`, that you have to use `.into()`, that `Update::xxx::skip()` is the same as `Skip.`, etc. And you can explore API without documentation, IDE will be your guide - just type `orders.`

### Probably interesting notes
- The old implementation of resolving futures (`Update::with_future_msg`) has a bug - it will blow JS stack - just try to increase iteration count in the last test `update_promises` in `vdom.rs` from `100` to, for instance, `5000` for Firefox (Chrome has a smaller call stack, so you need less iterations).
- I've solved that bug by wrapping up future in `NextTick` future (see `vdom.ts:425` and `next_tick.rs`). It seems fast enough - 100_000 `update` iterations in a few seconds.
- In that new example `orders`, I've included `gloo`s timers - pretty easy to use.
- Look at the same test at the end of `vdom.rs`, but this time in the PR / my branch:
  - I've merged `update_inner` and `update` and it returns `()` now so it's not possible to "hack" into "their" futures anymore for testing - I've solved it with `futures::oneshot`, which is a channel with the future on the one side and the input on the other one - just smuggle that input into `update` function through `model` and call it, when all async operations are done.
- I've added `pub const MX_EFF: i8 = 0;` into example `server_interaction_detailed/src/util.rs`, because I feel nervous when I'm creating PR which fails and I think that badge "build | failing" isn't good for marketing and contributions.

**Comment by David-OConnor** [comment]
Love it - both the changed update API (Even though it's breaking), and the improvements/additions.

**Comment by David-OConnor** [comment]
Appreciate the detailed example as well.
