### ISSUE TITLE
Dynamic Routing

### ISSUE THREAD

**Issue by rsaccon** [David-OConnor/seed#11]
I want to share one thought of mine about dynamic routing: The most mind-blowing simple but fully functional routing solution (based on `window.history`) I have seen so far is one written in ReasonML:
[Description](https://github.com/reasonml/reason-react/blob/master/docs/router.md)
[Code](https://github.com/reasonml/reason-react/blob/9e9e40ea4c7e8d55e56cba47a4d0188c26d0791e/src/ReasonReact.re#L947-L1050) 
Implementation is so much simpler than any of those react router implementations written in Javascript!

The secret sauce is just to split the URL (by `/`) into a `list` (ReasonML tail-recursive version of an array, or what in Rust is called `Vec`) of path segments, than the user of the api can recursively pattern match on that list to do his thing. 

I am new to Rust, but it seems to me Rust pattern matching should also allow to do something like that.

**Comment by David-OConnor** [comment]
Looks great - that's the best routing approach I've seen.

**Comment by thedodd** [comment]
I’m super stoked about this framework. The dynamic routing is pretty much the only thing blocking me from being able to fully adopt this for a production app (or at least starting to build it). 

@David-OConnor if you (or anyone else) is interested in joining the Rust WASM Working Group, I know a lot of folks would be happy to toss ideas around and do some hacking (myself included). 

Weekly, Thursdays. The team repo has more info. Will grab a link.

**Comment by David-OConnor** [comment]
Added partial dynamic routing in latest commit. See [todomvc example](https://github.com/David-OConnor/seed/blob/master/examples/todomvc/src/lib.rs#L186). Still need to specify landing page routing, same syntax as before, but now you can push to pages not included in it. Must pass app state down to routing messages, which adds verbosity, but no longer need to recursively call update.

**Comment by David-OConnor** [comment]
Published in v0.2.5
