### ISSUE TITLE
need suggest for making a rich text editor in seed

### ISSUE THREAD

**Issue by songmaotian** [David-OConnor/seed#114]
I am new to web，I read about some contenteditable, would it possible to define a tree-like document model, and  receive the edit event to map to the model? I try inputEvent, but the changed content does't appear.

or it would be better to use another tech to make a rich text editor?

**Comment by David-OConnor** [comment]
Can you post an example of the inputEvent that's not working as you expect?

This is something that can be made with any frontend framework, including this one. I imagine one approach is to store the tree however you like using Rust data structures (Nothing framework-specific), provide views which parse your tree, creating html elements as appropriate. Eg `div` with [contenteditable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-contenteditable) set to true, `p`s, `spans` etc which control formatting.

**Comment by MartinKavik** [comment]
If tree-like structure is not required for everything, read [Building a Text Editor for a Digital-First Newsroom](https://open.nytimes.com/building-a-text-editor-for-a-digital-first-newsroom-f1cb8367fc21) - they are using flat structure for paragraphs and their editor is based on [ProseMirror](https://prosemirror.net/).

You can also look at [Draft.js](https://draftjs.org/) and [Quill](https://quilljs.com/) for inspiration.

If you are new to web, I suggest to use something proven and study its API before you decide to create a library. However, It will be nice to have a modular rich editor in Rust if you decide to go the hard way.
But It always depends on project - maybe contenteditable will be enough for your project.

**Comment by David-OConnor** [comment]
Agree. I think the best approach is to find an existing one, and attempt to port it to your framework of choice, then modify as desired. Unless this is purely a learning project.

**Comment by songmaotian** [comment]
Thanks for all you suggest, I will try to learn one
