### ISSUE TITLE
Incorrect attribute string for SVG's viewBox

### ISSUE THREAD

**Issue by minno726** [David-OConnor/seed#116]
Seed renders the attribute `At::ViewBox` as `"ViewBox"`, but the correct attribute name is `"viewBox"`, without the capitalized first letter.

Ref: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox

Code: https://github.com/David-OConnor/seed/blob/a99285b7dc5a0b8e1ce9fb7b8f4693d899a2ade1/src/dom_types.rs#L591

**Comment by David-OConnor** [comment]
Will be in the next commit / release

**Comment by David-OConnor** [comment]
In latest commit and v0.3.5 release.

**Comment by minno726** [comment]
Yep, the new version fixes this.
