### ISSUE TITLE
Bug: Root elements order with seed::empty

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#119]
View code:

```rust
fn view(model: &Model) -> impl ElContainer<Msg> {
    // it has to be vec! and in root to reproduce bug
    vec![
        if model.show_first {
            // it works with div![] or span![], etc
            seed::empty()
        } else {
            div!["Something"]
        },
        button![
            "Toggle element",
            simple_ev(Ev::Click, Msg::ToggleElement)
        ]
    ]
}
```

**Expected order** after click on button "Toggle element" (It'll set `model.show_first` to `false`) :
1. div "Something"
2. button "Toggle element"

**Actual order**:
1. button "Toggle element"
2. div "Something"

Whole example: https://github.com/MartinKavik/seed/tree/fix/patch-seed-empty/examples/patch_seed_empty_bug_demo

---

@David-OConnor I noticed commit `Fixed a bug with rendering multiple Els from top level.` which can have something common with this bug and there are some todos - I don't want to change code under your hands and I suppose that you'll fix it more effectively than I do.
If you don't have time or there will be other obstacles, just ping me and I'll write tests and I'll try to fix it.

**Comment by David-OConnor** [comment]
I'll take this one. Likely caused by me improperly testing the latest patch.

**Comment by David-OConnor** [comment]
Fixed. The problem was the `next_node` parameter in `patch()` not being properly passed from `rerender_vdom()`.

**Comment by MartinKavik** [comment]
Nice! I've tried it in #121.
