### ISSUE TITLE
Bug: Postfix "px" for negative numbers

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#123]
```rust
div![
   style!{
       "left" => -50;
   }
]
```
renders `... left: -50 ...` instead of `... left: -50px ...`.

I didn't investigate it more, example with `format!` as workaround is in `/examples/animation_frame/src/lib.rs:144` (in PR: https://github.com/David-OConnor/seed/pull/122/files#diff-07b5ff47b0e764a7fb7dc61e7da3f6b8R144)

**Comment by David-OConnor** [comment]
Fixed in latest commit. Was a single-char change, in the style shim: 
```rust
 match val.parse::<i32>() {  // changed from u32
                Ok(_) => new_vals.insert(key, val_backup + "px"),
                Err(_) => new_vals.insert(key, val_backup),
            };
```

**Comment by MartinKavik** [comment]
Wow, that was quick.
Note: Code in that PR modified and force-pushed.
