### ISSUE TITLE
Proposal: Don't change properties order

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#124]
```rust
div![
   style!{
       "left" => 50;
       "top" => 100;
   }
]
```
renders `left` and `top` in random order so it's impossible to track changes in browser dev tools inspector and I don't know if it has some performance implications.

I didn't investigate other attributes or attributes order.

Example in `examples/animation_frame/src/lib.rs:139` (in PR https://github.com/David-OConnor/seed/pull/122/files#diff-07b5ff47b0e764a7fb7dc61e7da3f6b8R139)

**Comment by David-OConnor** [comment]
I'll take a look. I've been treating order as arbitrary, which is the cause of this.

**Comment by David-OConnor** [comment]
I think the root cause is that attributes are stored in a `HashMap`, which doesn't preserve order.

**Comment by MartinKavik** [comment]
Maybe https://github.com/bluss/indexmap can help.
Note: we should create `HashMap`s (including `IndexMap`) with simple hasher for better performance.

**Comment by David-OConnor** [comment]
Try the latest commit; changed to `IndexMap`.

**Comment by MartinKavik** [comment]
Nice! I'll look at it tomorrow.

**Comment by MartinKavik** [comment]
I tried it and it resolved this issue. I've added one change - see comments in referenced PR 125.
