### ISSUE TITLE
Proposal: Check style

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#125]
Problem - there are diffs in PRs only because of different formatting.

Ideas:
- CI should fail if formatting isn't correct (rustfmt [guide for Travis](https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server)).
- It should be impossible to merge into `master` if CI fails.
- Add a task into `Makefile.toml` - something like `cargo make format`. 
- Add pre-commit hook that will check formatting like CI (or execute formatting task).
- Add more linters - e.g. `clippy`.

I'll investigate it more and implement if you agree with it.

**Comment by David-OConnor** [comment]
Agree. I think we have different `cargo fmt` configs.

**Comment by David-OConnor** [comment]
I'm going to hold off on running `fmt` until we sort this out.

**Comment by MartinKavik** [comment]
>  Need to make sure it runs for the examples too, ie cargo fmt --all.

It's not enough because it ignores non-workspace examples (`server-integration` and `server-interaction-detailed`). It's resolved by using already implemented and updated task `for_each` (see associated PR).

> Do you know if there's a way to deterministically force a certain format config? Given there's no rustfmt.toml, I'm not sure why ours are formatting in different ways.

It was my mistake - I thought that IntelliJ Rust plugin uses only `rustfmt` but it uses also native formatter. However I've also added `rustfmt.toml` in PR and this problem won't happen again because of check in CI.

So before each commit we should run (we can force it in the future with pre-commit/push):
```
cargo make fmt_all
cargo make clippy_all
cargo make all
cargo make test_h firefox
```

**Comment by David-OConnor** [comment]
Can certainly group into 1.

**Comment by MartinKavik** [comment]
Naming is hard... how would you like to name that new task?
`check_all`, `verify_all`, `verify`, ...

**Comment by David-OConnor** [comment]
I like `verify` more than the others, and than any I can come up with.

**Comment by MartinKavik** [comment]
This issue can be closed after merge of PR 129.
