### ISSUE TITLE
Proposal: Find alternative to appending units to CSS values

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#127]
**Problem**
Automatic appending `px` to int values are very error prone:
- When I change number type (e.g. `i32` => `f64`) of the variable that represent some CSS value (e.g. "left"), Seed won't add `px` and CSS will fail silently in runtime.
- It's implicit - I have to know that rule and think about it while I'm writing styles.
- It adds `px` where it doesn't make sense - e.g. `z-index`.
- Some CSS properties allows to set both versions (integer with `px` and integer alone) - e.g. `line-height` => which version should be used?

**Solution**
- Remove automatic appending.
- Design a more explicit way to append units. Some quick ideas for inspiration:
  - A helper function: `"width" => px(car.width);`  (implemented in [PR 126](https://github.com/David-OConnor/seed/pull/126/commits/393bc8e8f3a0d1c9c521ed0a403015a620eab0d3#diff-07b5ff47b0e764a7fb7dc61e7da3f6b8R111)).
  - A macro/function: `"width" => unit!(car.width, "px");` (unit should be typed and we can call it also with enum: `"width" => unit!(car.width, Unit::Pixel);`.
  - Update original `style!` macro (if possible): `"width" => car.width "px";`.

I'll implement it if we agree on something.

**Comment by David-OConnor** [comment]
Need to think on this. This automatic adding of `px` is controversial in React for the reason you mention. I think in the majority of cases, the current behavior simplifies code, so perhaps we could address the edge cases individually. Eg don't apply for `z-index`, `line-height` etc. Alternatively, maybe getting rid of this behavior is good to keep behavior consistent.

**Comment by David-OConnor** [comment]
[Related[https://github.com/facebook/react/issues/13567)

**Comment by MartinKavik** [comment]
Yeah, I was studying it in the afternoon, I think that only jQuery and React append `px`.
Nice quote from that issue:

> yeah I think the auto px append is a bit of a relic, it probably was inspired by jQuery (tho we'd have check with the old timers on that one..

And there is jQuery issue:
- https://github.com/jquery/jquery/issues/4009
---

>perhaps we could address the edge cases individually. Eg don't apply for z-index, line-height etc.

There is the [React's list](https://github.com/facebook/react/blob/4131af3e4bf52f3a003537ec95a1655147c81270/src/renderers/dom/shared/CSSProperty.js#L15-L59) from its [docs](https://reactjs.org/docs/dom-elements.html).

**Comment by David-OConnor** [comment]
I think your suggestion of the helper fn `px` is my fav approach (fine as-is in your PR), and making a breaking change where implicit `px` is no longer added is the best solution.

**Comment by David-OConnor** [comment]
Should add `q`, `mm`, `cm`, `in`, `pt`, and `pc` as well; can all call a single helper fn to reduce repetition.

**Comment by MartinKavik** [comment]
I'll try to implement it so we see how it looks in practice.
