### ISSUE TITLE
Automate release flow

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#137]
Current release flow:
1. update change log
1. test
1. commit + push
1. package
1. publish
1. add GitHub release
1. update homepage + a script that updates docs links

Let's focus on this issue before next release.

**Comment by David-OConnor** [comment]
First step: Attempting to integrate the homepage as a normal example, while still being able to host from the (now main) repo. Should be able to modify the Python script to build markdown files from the changelog and readme to prevent it them being repeated. Could convert it to a Rust file to integrate better with cargo make, and prevent having to have Python installed.

**Comment by MartinKavik** [comment]
> Attempting to integrate the homepage as a normal example

Wait with it please.
1. I'm afraid that it will complicate Seed repository and tasks or deploy, but maybe I'm wrong.
2. I'm learning routing while writing [realworld](https://github.com/gothinkster/realworld) example and then I want to try redesign homepage and write it in a quickstart to learn working with markdown in Seed. So it's possible that my results won't be good but maybe it saves you a little bit work / time.

**Comment by David-OConnor** [comment]
Anything you'd like to add/change etc before next release?

**Comment by MartinKavik** [comment]
My notes / ideas:
- I think that your contributing guidelines will improve quality of new PRs.
- Can I ask you a favor? Could you please develop in non-master branches and then create PRs (you can merge it immediately after creating of course). It will be easier to find out new changes / features, it will be easier for you when you are resolving conflicts and you won't have to write comments like _Added xxx in latest commit._. And it will be easier to search for e.g. missing commits and recreate changelog from history of PRs.
- `Anything you'd like to add/change etc before next release` - if you can look at https://github.com/David-OConnor/seed/issues/151#issuecomment-504466749 and https://github.com/David-OConnor/seed/issues/158 I would be happy (1st problem is weird and 2nd is annoying when I'm testing realworld example). Both shouldn't be very time consuming (I hope so).

That's all for me, your turn before / after release :)

**Comment by MartinKavik** [comment]
Idea: Add RELEASE_CHECKLIST.md - something like https://github.com/rustwasm/wasm-pack/blob/master/RELEASE_CHECKLIST.md

**Comment by David-OConnor** [comment]
https://github.com/David-OConnor/seed/pull/203

**Comment by MartinKavik** [comment]
`RELEASE_CHECKLIST.md` exists and if I remember correctly, there were no serious problems with releasing recently. I'm closing it, because we can update checklist directly when we find out some problems.
