### ISSUE TITLE
Proposal: Macros raw! and markdown! 

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#140]
Can I add macro `raw!`?

Motivation
Before:
```rust
El::from_html("&nbsp;")
```
After:
```rust
raw!("&nbsp;")
```

---

And `markdown!` or `md!`?

**Comment by David-OConnor** [comment]
I don't see harm in having the option; it's more concise, and macros in the global namespace aren't a big deal since they don't conflict with non-macros of the same name. Generally, I prefer to use macros only when they provide things functions don't provide. We can have both.
