### ISSUE TITLE
Bug: Typos in attributes

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#141]
Typos
- `OnRateChangen` => `OnRateChange`
- `Hreflang` => `HrefLang`
- `OnDragend` => `OnDragEnd`
- `OnPopstate` => `OnPopState`
- `Onsuspend` => `OnSuspend`
- `PlaceHolder` => `Placeholder`

Can I fix it?

**Comment by David-OConnor** [comment]
Go for it!
