### ISSUE TITLE
Proposal: Comma (,) sepator for attrs! and style!

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#142]
Proposal: Allow to write `attrs!` and `style!` also this way:
```rust
attrs!{At::Type => "text", At::PlaceHolder => "Article Title"}
```
I'll implement it if you agree.

**Comment by David-OConnor** [comment]
Go for it. I originally wanted to have both, but ran into technical issues, which I think a recent PR of yours fixed. Semicolon's more consistent with CSS/inline styles. Comma's more natural for Rust. (Although lack of a built-in HM literal leaves the correct answer biguous). Both options avail's the way to go.
