### ISSUE TITLE
Bug: Attribute xmlns in elements created by El::from_html

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#145]
`El::from_html` adds automatically atrribute `xmlns` into every HTML element.

How to reproduce:
1. Add this code somewhere into view (I used orders example):
```rust
El::from_html("<div><span>X</span></div>"),
```
2. Start given example and inspect it in browser:
```html
<div xmlns="http://www.w3.org/1999/xhtml">
    <span xmlns="http://www.w3.org/1999/xhtml">X</span>
</div>
```

**Comment by MartinKavik** [comment]
There is problem also in `El::from_html`, try to inspect code in https://seed-rs.org/.

**Comment by David-OConnor** [comment]
Fixed in latest commit. Due to vdom Els created from web_sys Elements automatically inserting namespace.

**Comment by MartinKavik** [comment]
Nice!
