### ISSUE TITLE
Events from SVG 

### ISSUE THREAD

**Issue by tiberiusferreira** [David-OConnor/seed#148]
Hello, it's very exciting to see Seed evolving.

I was wondering if there is a way get events from a SVG. Should/Can I rewrite the SVG using the svg! macro and attach events to it? 

I tried doing it, but did not get very far:
```
   let a:  El<Msg> = svg![
     g![
     class!["grid x-grid"],
     line![attrs!["x1" => "90"]]
     ]
    ];
```

Gives me: 
```
error: line! takes no arguments
  --> src/lib.rs:45:6
   |
45 |      line![attrs!["x1" => "90"]]
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `update` found for type `u32` in the current scope
  --> src/lib.rs:43:6
   |
43 | /      g![
44 | |      class!["grid x-grid"],
45 | |      line![attrs!["x1" => "90"]]
46 | |      ]
   | |______^
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

The whole svg code is here: https://github.com/tiberiusferreira/gringos_shower_monitor/blob/9b375422188a6981834dbead33f986f5cb8784c5/src/lib.rs#L40

Is this something Seed does not support yet?

**Comment by David-OConnor** [comment]
Try using `line_!` instead of `line!`: The latter is [reserved by rust](https://doc.rust-lang.org/1.2.0/std/macro.line!.html), so we use this instead to deconflict.

**Comment by tiberiusferreira** [comment]
Thanks it works. 
There are some svg elements still missing, such as ```<title id="title">Some Title</title>``` right? 
Is there something blocking support for them ?

**Comment by David-OConnor** [comment]
Nothing blocking. Do you know which others are missing?

**Comment by tiberiusferreira** [comment]
I don't, I just bumped into that one. I'll try to find a list online and test against it.

**Comment by David-OConnor** [comment]
Don't worry about finding the list; already in the todos in `shortcuts.rs`. The `Tags` exist, but not macros for a number of SVG elements.

**Comment by tiberiusferreira** [comment]
Closing since the original issue was solved. Thanks for making Seed awesome!
