### ISSUE TITLE
Food for thought : WebRender backend in addition to DOM

### ISSUE THREAD

**Issue by codri** [David-OConnor/seed#15]
Hi,

I like the direction the project is going with regards to the view templates, it looking like the Elm view DSL, rather than JSX, as well as the Elm inspired app model. As a matter of fact, I've been making such a DSL myself, but this implementation seems to be much more complete.

One idea that I considered interesting is in addition to working with DOM, is to wrap WebRender(https://github.com/servo/webrender) to make native widgets, sort of like this project (https://github.com/cztomsik/node-webrender), but the output would be entirely native binaries(and given WebRender is moving to use the native libraries as much a possible, the binaries should be very small as well).

I'm very much planning to do that, that being said, it might become a side project that goes nowhere.
So, wanted to ask if this project only plans to target the web via DOM.

Thanks

**Comment by David-OConnor** [comment]
I'm not familiar with WebRender. My intent was to only target the DOM, but if it makes sense, we can add this. At a glance, this looks related to WebGl, which I have some experience with.

**Comment by codri** [comment]
So, WebRender is a 2dish API, there are a couple of nice reads that describe its place in the stack(https://pcwalton.github.io/slides/201808-webrender/) (https://nical.github.io/posts/rust-2d-graphics-02.html) (https://nical.github.io/posts/rust-2d-graphics-01.html).

It's more like a replacement for Skia 2d library. There are a couple of interesting things going for it:
1. It's supposed to do most of the work on the GPU(including font-rendering, thanks to pcwalton/pathfinder), which should allow for more elements and smoother UIs
2. It's supposed to be lightweight, thanks to reusing system libraries(font-loading via pcwalton/font-kit which wraps native font management tools), compositing (pcwalton/planeshift which wraps native compositors)
3. Handles animation natively
4. Handles batching natively(one just sends a list of drawing commands as is, and it takes care to batch similar drawing commands, and do some layering)
5. It has an interesting API where one passes different drawing commands and it takes care of rendering the list efficiently(that's the interesting thing as there is no dom per se, and it might be faster to just re-render all the time, it's structured more like a game engine, but I'm yet to have a more thorough investigation)
6. The plan to is to use this in Firefox, which makes it a good bet
7. There are discussions of it being implemented on top of gfx-hal, which means it will run with vulkan, metal, opengl and most likely webgl(https://github.com/servo/webrender/issues/407)
8. It has a fast path for shadows and boxes(explained by nical in one of his posts)

I've noticed there is a plan to wrap fetch api, obviously for making desktop apps stdweb api's won't be available, so one would have to do an implementation that calls into reqwest or something when not compiling for wasm. Thinking about it, it might become tricky to make the apps compile seamlessly for web and native, and could be out of the scope of this project. I assume the plan is to expose a series of web apis, and reimplementing standalone versions of them might turn out to be a pain, nevertheless, it's an interesting exercise to think about how this could be made.

Btw, good idea of nesting different macros for the UI views, I went with recursive macros and having one top level macro view![] and trying to handle different elements inside it like `view![div ["text "] ]` which didn't work in a lot of cases, so I had to backtrack to procedural macros, which I'm yet to implement.

**Comment by rsaccon** [comment]
@codri thanks for sharing your thoughts on webrender. Of course it would be amazing to have shared abstraction for web and native components. I did recently myself some research on this and I am following the progress of [azul](https://github.com/maps4print/azul), which is maybe the most mature (but still very alpha) desktop GUI framework using webrender. Here my thoughts on it:
- It is low level, way more low-level than e.g something Electron based
- It is low level, e.g. scrolling is not provided. The GUI frameworks I looked at, implemented yoga based layout engine, the same as in react native for flex layout.
- Binary sizes of simple apps I toyed around with were about 10 MB, way less than something Electron based. Also they consume very little memory while running, compared to Electron.

**Comment by codri** [comment]
@rsaccon with regards to layout, I like the way flutter did it, the layout primitives are widgets and wrap other widgets, it's cleaner in my opinion, that being said to tinker with the style one would have to recompile the app every time, which is not a problem in Dart, but can become unpleasant in Rust.

That's why I also was thinking about the templating engine being separate, maybe even use something like glimmer-vm, which I think was supposed to be rewritten in Rust, and add a webrender backend to it, that way the templates would be handlebar ones(not sure about how styling and layout fits in this picture) and one would develop the templates with a fast feedback loop, separately from the app logic, sort of like react pure components. Then wrap the templates into custom widgets(elements), that seems to be done one level above glimmer-vm, in ember.

Anyway, that's one more thing I'll have to investigate. Will update this thread if I think this could be incorporated into seed. Maybe it doesn't make sense to mix the concerns, that being said, a framework that could seamlessly target web and native UIs would have a big advantage over the competitors.

**Comment by rsaccon** [comment]
@codri I like very much the idea of a seperate layout engine based on glimmer-vm. I am not familiar with glimmer it as it is now, but I messed around a lot with ember before react got popular. 

About the layout engines, flutter is based on the cassovary approach. There is apparently a [rust implementation](https://github.com/dylanede/cassowary-rs) for it, but one thing to consider: Don't we want to make it similar to the DOM implementation (which is natively flex based)? In Flutter hummingbird (their web implementation), they have their own rendering engine, canvas based (and experimenting with CSS-Paint). For Flex layout there is [Rust wrapper for yoga](https://github.com/bschwind/yoga-rs).

About styling, maybe something non-cascading CSS-like ? I think Azul has come up with a sophisticated solution for that.

**Comment by handicraftsman** [comment]
Scrolling in azul will actually be supported.

**Comment by David-OConnor** [comment]
Closing this; out of the project's scope, in the near-term.
