### ISSUE TITLE
Documentation for set_text is confusing

### ISSUE THREAD

**Issue by spersson** [David-OConnor/seed#151]
The example below did not render as I expected. I expected a td containing a span with text. Instead what I get is a td with text.

```rust
 let mut content = span![class!["node"]];
content.set_text(text);
td![content]
```

I wasted quite some time trying different solutions and fiddling around, reading seed sources and github issues.
I tried changing the set_text call to a add_child, adding a span. But then I get a span in a span in a td. Finally i found that adding an El::new_text() works. (Took some time before I tried that because I saw the source of it that it creates a span so I didn't think it would make a difference, but it did.)

In the end the whole issue was my misunderstanding of how things work. Please update documentation.

Perhaps the set_text method should say something about changing the element in such a way that it doesn't matter what tag this element has, that it will "turn into" or "used as" a text of it's parent node.  Suggest that if you want to add text to *this* node you should use add_child(El::new_text(t)) instead.

Thanks!

**Comment by David-OConnor** [comment]
This is a bug: `set_text` is intended to work as you expect.

**Comment by MartinKavik** [comment]
> I wasted quite some time trying different solutions and fiddling around

Me too, I wanted to create issue but @spersson was faster. 

---

While we are changing/fixing/documenting `El` API I also suggest to return `self` from `El` methods like `add_child` or `set_text` so we can chain them and remove `mut` from declaration:
```rust
let content = 
    div![]
        .add_child(span![])
        .add_child(span!{})
```

---

> Suggest that if you want to add text to this node you should use add_child(El::new_text(t)) instead.

Or `add_child(plain!(t))` after the next release (merged PR: https://github.com/David-OConnor/seed/pull/149)

**Comment by David-OConnor** [comment]
In latest commit. Applied to initial issue:
```rust
let content = span![class!["node"]]
    .set_text(text);
```

May need to modify so `set_text` purges existing text children.

**Comment by MartinKavik** [comment]
> May need to modify so set_text purges existing text children.

It sounds to me a little bit dangerous / surprising for users. What about change name from `set_text` to `add_text` or `add_text_child`?

---

`// todo: Allow text to be impl ToString?`
When I'm not sure if I should allow more options I'd rather wait for real-world problem. Allowing more options is always easier than make it more strict in the future as a breaking change.

**Comment by David-OConnor** [comment]
Maybe both: modify this fn's name to `add_text`, and add a new `replace_text`. I don't want to include `child` in the name, since I think of the fact that text's added as a child text node is a DOM implementation detail; it's not even obvious from HTML that that's going on.

**Comment by MartinKavik** [comment]
Yeah, I agree with you on `_child`.

---

```rust
let mut my_element = div![
    "TextA",
    div![],
    "TextB"
]
```
=> how would be element changed when we call `my_element.replace_text("TextC")`?

**Comment by spersson** [comment]
Perhaps the best is to just remove the set_text method for now? Seems like not used much if it took this long for the problem to be reported. And the needed semantics is now being argued (add_text, replace_text). Are you guys sure this is needed? Wait until there is a clear need?

Another thing, part of what confused me (just implementation). It seems like if the "text" field of El is Some, then none of the other fields should be used? In that case I would think it could be nicer to remove the text field and have
```rust
enum Node<Ms> {
    Text(String),
    Dom(El<Ms>)
}
pub struct El<Ms> {
...
   pub children: Vec<Node<Ms>>, 
}
```
But of course I have not looked at this in any detail. Just an idea, At least it would make it impossible to set attributes, styles and such on plain text...

**Comment by David-OConnor** [comment]
You're right that I don't think this method will be used frequently compared to declaratively creating elements with macros, but it (now that it's fixed) is easy to understand. I don't think it's cluttering up the API.

You're right about how the `text` field works. `None` means an [Element node](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType), and `Some(...)` means a `text` node, which then ignores most of the other fields. Perhaps your suggestion is easier to understand.

**Comment by David-OConnor** [comment]
Latest commit renames `set_text` to `add_text`, and adds `replace_text`.

**Comment by MartinKavik** [comment]
> Latest commit renames set_text to add_text, and adds replace_text.

Maybe I have some problem with cache but I can't find `replace_text` and a new commit.

**Comment by David-OConnor** [comment]
I dorked up the push; try now.

**Comment by MartinKavik** [comment]
I've added some comments (https://github.com/David-OConnor/seed/commit/5f5580a7b3b488c0c1af5d9c7c96d0b647326949) but looks good. Thanks,
