### ISSUE TITLE
implement MessageMapper for Listener

### ISSUE THREAD

**Issue by CallumJHays** [David-OConnor/seed#152]
Currently `Listener` has its own private implementation for `map_message()`:
https://github.com/David-OConnor/seed/blob/632b134e7b74aa493a2ff9207c974da53321088a/src/dom_types.rs#L373

I think `Listener` should instead implement `MessageMapper`, also making it public so that I can remap subscriptions from any subcomponent modules

**Comment by MartinKavik** [comment]
I wasn't fast enough to write comments for merged PR, so my notes:

1. There are two implementation for `Listener`'s `map_message` now (the [first](https://github.com/David-OConnor/seed/blob/master/src/dom_types.rs#L373), the [second](https://github.com/David-OConnor/seed/blob/master/src/dom_types.rs#L391)). So we should remove the private one. @CallumJHays could you fix it please?

1. Commit message [_"new comp, hadn't activated auto-rustfmt"_](https://github.com/David-OConnor/seed/pull/153/commits/6811f8e9f5d3fc6edb159e6fbdd23230dc061018):
    - We should squash commits into one in the most cases.
    - _"hadn't activated auto-rustfmt"_ - we have task `cargo make verify` for this, it should be run before every commit / push.  @David-OConnor  Maybe we should write guide for contributing and/or pull request template (https://github.com/David-OConnor/seed/community).

3.  `fn map_message(self, f: fn(Ms) -> OtherMs) -> Listener<OtherMs> {` ([code](https://github.com/David-OConnor/seed/blob/master/src/dom_types.rs#L373)).

Thanks.
    -  @CallumJHays Does `rustfmt` or you changed `Self::SelfWithOtherMs` to `Listener<OtherMs>`?
       It was my hint for developers that `map_message` should return the same entity but with only changed generic type (e.g. `Listener<Ms>` to `Listener<OtherMs>`. I was unable to force this rule with Rust type system, because it doesn't support something like `Self<Ms>` to `Self<OtherMs>` (or I didn't find a way).

**Comment by CallumJHays** [comment]
Thanks for the notes!
1. LOL oops, sorry I didn't expect the PR to get merged, just did what worked for me locally without paying much attention :P
2. I'll be sure to run cargo make verify before each PR in the future.
3. I like your suggestion, I think it would make the docs a lot clearer with the 1 less level of indirection. Yeah it's unfortunate that `Self` doesn't work like that.

On it
