### ISSUE TITLE
add_class method

### ISSUE THREAD

**Issue by spersson** [David-OConnor/seed#156]
Style is a dom node attribute but El stores it not in attrs but in a seperate field. That makes it much nicer to work with than if it was only a At::Style => "all my css here".

In a similar way, could it not make sense to treat the class attribute in a special way? The current class macro is not bad, but I think it would be better to have a add_class method on El. Store classes in a Vec<String> in El, I guess..
What I do now in my functions is to create a local Vec, conditionally push classes to that and then finally make use of it via Attrs::add_multiple(). Works but not as nice.

I am just a beginner when it comes to web development but it seems that conditionally adding multiple classes to a node is very common.

**Comment by MartinKavik** [comment]
> it seems that conditionally adding multiple classes to a node is very common

Look at the updated `class!` macro - https://github.com/David-OConnor/seed/pull/150#issuecomment-503769438

**Comment by David-OConnor** [comment]
I think `add_class` would be a good addition. A [recent PR by @MartinKavik ](https://github.com/David-OConnor/seed/pull/150) added the ability to add conditions in the `class!` macro.

**Comment by David-OConnor** [comment]
Added `add_class` in latest commit.
