### ISSUE TITLE
Bug: Jumping cursor

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#158]
Test case:
1. `cargo make start counter`
2. Click to the input with text `click` - place cursor somewhere before the last letter, e.g.  `c|lick` 
3. Write something (e.g. `x`) and observe - you should see `cxlick|`

I tried to reset master branch before we merged sync with animation frame but it seems that this bug was here from the beginning.

I was googling a little bit and it seems that every second person encountered this - jQuery, React, plain js..

I'll try to fix it somehow.

**Comment by MartinKavik** [comment]
I investigated it a little bit, see referenced PR #159 for more info.
@David-OConnor I don't want to change code under your hands and I think that it will we more effective when you fix it while you are refatoctoring events & listeners.

**Comment by MartinKavik** [comment]
@David-OConnor Do you have something in progress or can I fix it?

**Comment by David-OConnor** [comment]
Have at it - Nothing on my end.

**Comment by MartinKavik** [comment]
Bug seems to be fixed on desktop browsers (Firefox + Chrome on Windows), but it still jumps on iOS (Safari + Firefox). You can test it with https://seed-rs-realworld.netlify.com/  (for example on Sign-in form).

Possible solution is to remember cursor position before calling `set_value` and then set it to previous value (inspired by https://github.com/facebook/react/issues/955#issuecomment-469344232).
Or we can experiment with `orders.force_render`.

P.S. @David-OConnor  I will be without PC for about two weeks in August, so I can't start working on it until the second half of August.

**Comment by David-OConnor** [comment]
That RWE looks great!

**Comment by MartinKavik** [comment]
Update: `wasm-bindgen` with required `HTMLInputElement` methods has been released: https://github.com/rustwasm/wasm-bindgen/releases/tag/0.2.52
