### ISSUE TITLE
panicked at 'Missing child el_ws'

### ISSUE THREAD

**Issue by flosse** [David-OConnor/seed#166]
Unfortunately I get a `panicked at 'Missing child el_ws'` from time to time. I haven't found the problem yet.
Do you have an idea how to nicely debug a `seed` app?

**edit**: I'm using seed `v0.3.7`

**Comment by flosse** [comment]
I found a workaround: https://github.com/flosse/seed/commit/72b66f6628ee10bb0bace1798f110e51498e8e50 that seems to work at least for now.

**Comment by MartinKavik** [comment]
I've seen it a few times when I was furiously switching between two pages by clicking on menu buttons and browser was reloading (this bug is fixed on master, it isn't reloading now (https://github.com/David-OConnor/seed/issues/163)). So I think that it can be somehow related to initializing / destroying DOM by browser while the Seed is running patching algorithm.

**Comment by flosse** [comment]
I tried b728b97b but it's the same :(

**Comment by MartinKavik** [comment]
Also If you try to repeatedly press F5, you can see something like this in dev tools console:
```
`WebAssembly.instantiateStreaming` failed. Assuming this is because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
 DOMException: "The operation was aborted. " package.js:1831:25
TypeError: "Body has already been consumed."
    result http://localhost:8000/pkg/package.js:1833
```

Yeah and sometimes (like me at the moment) you get your error: `panicked at 'Missing child el_ws', src/libcore/option.rs:1034:5`.

@David-OConnor I think we can use @flosse 's workaround like a starter point and change patch panics into checks + `logs` before we deal it properly (if it's possible to handle it).

**Comment by flosse** [comment]
> @David-OConnor I think we can use @flosse 's workaround like a starter point

no, I would not recommend that because it just introduces a new bug (the DOM is dirty afterwards).
I think it's better to know why there is no child available.

**Comment by MartinKavik** [comment]
@flosse  do you have a public repo / example when are you testing it?

**Comment by flosse** [comment]
> @flosse do you have a public repo / example where are you testing it?

no not yet. I think at the end of the year I'll have a public project that will (probably) use seed.

**Comment by MartinKavik** [comment]
I'm able to pretty reliable reproduce it in realworld example:
- Open `http://localhost:8000/settings` (you have to be logged in)
- Press F5 and immediately click on `New Post` => panic `Missing child el_ws`
So I try to debug it.

**Comment by MartinKavik** [comment]
@David-OConnor I think we can close it.
