### ISSUE TITLE
DOM-mutating JS libraries usable with Seed?

### ISSUE THREAD

**Issue by dave-doty** [David-OConnor/seed#168]
I recall that libraries mutating the DOM don't play well with Elm, since Elm wants to "own" the DOM underneath the node where it resides. I'm not sure what is the related story with Seed.

For instance, I want to use Seed to build an application that in a sub-node renders some SVG, and I'd like to use a JS library such as this one that modify the SVG nodes: https://www.npmjs.com/package/svg-pan-zoom (in this example the library allows panning and zooming by setting different transforms on a root element to translate and scale the SVG elements under it)

I know in Elm this would be problematic because Elm would expect to be the only one writing to the DOM nodes representing the SVG, and it would cause inconsistencies for the JS library also to mutate these nodes.

Is Seed similar in expecting to "own" the DOM? Is there an officially suggested way to use JS libraries such as this one alongside Seed?

**Comment by MartinKavik** [comment]
We've got problems with font-awesome (https://github.com/David-OConnor/seed/issues/89#issuecomment-497388194) so I think it would be problematic, if possible.

**Comment by David-OConnor** [comment]
As far as I know, this is an issue with most (all?) frontend frameworks. Ie applies to React etc too. You can give individual manipulations a shot, but they may cause conflicts with the VDOM renders.
