### ISSUE TITLE
make map_message generic

### ISSUE THREAD

**Issue by spersson** [David-OConnor/seed#169]
I encoutered a problem when trying to grow my app into having a sub - (view/update/Msg/Model).
```rust
fn view(model: &Model) -> Vec<El<Msg>> {
    let sidebar = div![
        class!["sidebar"],
    ];
    let mut result = vec![sidebar];
    for (prop_id, prop) in &model.properties {
        result.push(property::view(prop).map_message(|m| Msg::Property(prop_id, m)));
    }
    result
}
``` 

This will not compile because map_message is not accepting closures, needs to be generic to do that.
In my case it has be a closure since it is dynamically adding an unique identifier to each message.

**Comment by MartinKavik** [comment]
Yeah, I encountered it a few times, too.  In `map_message` and I think also in event handlers.

I wanted to change it, but it's not a super simple, because there are many dependencies.
So my "workaround" looks like this:
```rust
impl<Ms: 'static, GMs> Effect<Ms, GMs> {
    pub fn map_message_with_fn_once<OtherMs: 'static>(
        self,
        f: impl FnOnce(Ms) -> OtherMs + 'static + Clone,
    ) -> Effect<OtherMs, GMs> {
        match self {
            Effect::Msg(msg) => Effect::Msg(f(msg)),
            Effect::Cmd(cmd) => Effect::Cmd(Box::new(cmd.map(f.clone()).map_err(f))),
            Effect::GMsg(g_msg) => Effect::GMsg(g_msg),
            Effect::GCmd(g_cmd) => Effect::GCmd(g_cmd),
        }
    }
}
```

**Comment by jgrund** [comment]
I'm hitting this quite a bit as well. Would be very useful to have this closure support.

**Comment by MartinKavik** [comment]
> also in event handlers.

Like this one:
```rust
form![
    raw_ev(Ev::Submit, |event| {
        event.prevent_default();
        Msg::FormSubmitted(article_slug) // fails because of article_slug
    }),
...

I'll try to implement support for clusures for map_message and event handlers.
@David-OConnor Do you agree?
```

**Comment by David-OConnor** [comment]
Yep

**Comment by MartinKavik** [comment]
All handlers and mappers should be able to receive `FnOnce` now. So I think we can close it or wait to next release so @spersson (@jgrund ) will be able to test it.

**Comment by David-OConnor** [comment]
Closing, due to @MartinKavik 's fix.
