### ISSUE TITLE
WebSocket example question

### ISSUE THREAD

**Issue by TatriX** [David-OConnor/seed#173]
What is the reason behind extracting `ws` in [websocket example](https://github.com/David-OConnor/seed/blob/master/examples/websocket/src/client.rs#L105) from the `Model`?

**Comment by MartinKavik** [comment]
Because we needed app instance in callbacks, I've refactored it from older example if I remember correctly.
I think you can use it in a standard way in `update` function now because app instances has been replaced with `seed::update(Msg::Sent);`. And I'm planning to create a PR in next weeks which adds possibility to get  the app instance from `orders` in `update` function so it will be easier to use callbacks.

**Comment by TatriX** [comment]
Yep, it works just [fine](https://github.com/TatriX/play-with-me-seed/blob/master/src/lib.rs#L96). I was just wondering if there are any particular reasons why I shoudn't do it this way. Thanks!

**Comment by TatriX** [comment]
One thing bothering me that adding `ws` to ones `Model` makes it kinda unpure. You can't easily construct and test it, or for example easily use time travel debugger if any.

So I looked at [elm](https://package.elm-lang.org/packages/elm-lang/websocket/latest/WebSocket) implementation and they use a trick where `send`ing is using socket uri instead of handle. Then if you also subscribed for messages from the same `uri` runtime will manage that socket for you instead of closing it immediately after sending.

Maybe something similar could be useful as a higher lvl API.

**Comment by MartinKavik** [comment]
> Maybe something similar could be useful as a higher lvl API.

Yeah, there are more modules which should be designed and implemented as a higher level API (Local storage, better Fetch, etc). But at the moment is imho more important to have a stable core.
However you have a good ideas and there is already thread about websockets (https://github.com/David-OConnor/seed/issues/8) so I think we can close this issue and continue there. Also you can look at websocket issues https://github.com/rustwasm/gloo and help with it.

**Comment by TatriX** [comment]
Sure!
