### ISSUE TITLE
chainable methods in 0.3.7

### ISSUE THREAD

**Issue by spersson** [David-OConnor/seed#179]
I just updated from 0.3.6 to 0.3.7 and noticed that all calls to add_child on elements no longer compile. I see that there was a change in function signature to allow chaining, which is a goal I can understand. But now because the method takes over ownership I need to change lots of callsites to look like this
```rust
// before: header.add_child(menu);
header = header.add_child(menu);
```

Could chaining not be better achieved by having these methods accepting &mut reference like before but just also return that mut ref? That would avoid these pointless assignment statements.

As always, thanks for good work!

**Comment by David-OConnor** [comment]
I agree that it'd be nice to have both styles. Initial hack at doing so with the same method unsuccessful. Looking at what options we have (other than having separate mutate methods).

**Comment by spersson** [comment]
Your comment made me doubt myself since I have never actually written chainable any methods. I tested it in [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=78ed94646196ffdd49bfbfffd8512876) and seems to work fine in this simple case at least.

**Comment by MartinKavik** [comment]
@spersson Could you pls paste here/to gist a sample code where you are using some chains? (It would be nice to have some examples of the API updated in #206.)

**Comment by spersson** [comment]
Chainable methods was a change between 0.3.6 and 0.3.7. I don't know what the motivation (specific usage scenario) was. I mostly see it as a "why not" type of thing. But the way it was done, with taking ownership and returning ownership instead of using mut refs was causing friction.

If we go back to why these "add_xxx" Node methods even exist... In my thinking there are three ways to create a Node<Msg>:
1. Declarative style using macros. This is the preferred option, easy to see the tree structure and which attributes apply to which nodes. Can have optional nodes by use of empty nodes in the else clause. Breaks down when there is complicated logic for adding nodes or setting attributes, especially if generated by iterator or such. Options 2 and 3 are better then.
2. First create Vec with child nodes that should be added, done with regular imperative or functional style rust. Then use that vec in a declarative seed macro at the end. Looks a bit ugly when creating lots of Vecs on the stack just for the purpose of handling all scenarios of optional child nodes and attributes.
3. As an alternative to option 2, first create a basic Node<Msg> with macro, then use these add_xxx methods to modify. Looks better.

Example code which uses option 3:
```rust
fn view_template_menu(templ: &Template) -> Node<Msg> {
    let mut menu = div![class!["contextmenu"]];
    match &templ.focus {
        Focus::PropertyFocus(prop_id, f) => {
            property::view_context_menu(&templ.properties[*prop_id], &mut menu, f, *prop_id);
        }
        Focus::Nothing => {
            menu.add_child(button("Add Property", Msg::AddProperty(None)));
        }
        Focus::TemplateParent(_) => {}
    }
    menu
}
```
In this example it would have been messy to use option 1, putting all the logic inside of the div! macro. Using the add_child macro in just one of the three branches looks better than returning empty nodes in the other branches.

So my argument is that these add_xxx methods are very nice to use for the more complicated node building situations. But taking and returning ownership does not suit this style of usage.
In all the seed examples which had to be modified in this PR there is no actual good example of why those methods are used, they are just there to demonstrate that the methods exist.

**Comment by MartinKavik** [comment]
Thanks for explanation!

> Chainable methods was a change between 0.3.6 and 0.3.7. I don't know what the motivation (specific usage scenario) was.

Related https://github.com/David-OConnor/seed/issues/151#issuecomment-503986605. Those methods weren't chainable at all - so this was the main reason. (I wanted it in one of my projects).
And the reason why they have type `self` instead of `&mut self` - so you don't have to use mutability just because of API **(1)** and you don't have to create dummy elements when you are using these methods for constructing/extending elements **(2)**.

Ad **1)** - Your example rewritten to use the current API:
```rust
fn view_template_menu(templ: &Template) -> Node<Msg> {
    let menu = div![class!["contextmenu"]];
    match &templ.focus {
        Focus::PropertyFocus(prop_id, f) => {
            property::view_context_menu(&templ.properties[*prop_id], menu, f, *prop_id)
        }
        Focus::Nothing => {
            menu.add_child(button("Add Property", Msg::AddProperty(None)))
        }
        Focus::TemplateParent(_) => menu
    }
}
``` 

Ad **2)** (Probably used only in tests at the moment)
```rust
let content = 
    div![]
        .add_child(span![])
        .add_child(span![])
```

---

So I think both version (`self` and `&mut self`) are useful (as @David-OConnor suggested in https://github.com/David-OConnor/seed/issues/179#issuecomment-509930903).

I agree with @spersson that `&mut self` is a better default option because when I see something like `menu.add_child(button("Add Property", Msg::AddProperty(None)))` I assume that it mutates `menu` and returns `()` or child or reference to `menu`.
And it will be probably more comfortable to use when you decide to write nested functions which modify given element.

So that I suggest to merge PR https://github.com/David-OConnor/seed/pull/206 and we can add alternative methods like `into_add_child` in the future if necessary.

**Comment by spersson** [comment]
@MartinKavik : good comments!
After reading again, I think the only thing I have to say on this topic is to emphasize that these methods are really only necessary when things get really messy, when using rust expressions inside macros really would not work because you would get 15 levels of indentation. My example was still too simple... that's why your rewritten version of it actually looked quite good. :)
I have not yet seen a need for calling methods like your second example, where indeed on owned data works much better. I agree that it can always be added later if the need arises.
Thanks for good discussions! Closing issue since PR 206 is merged.
