### ISSUE TITLE
VirtualNode

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#180]
Idea:
Introduce something like `VirtualNode` - its variants wouldn't have `node_ws` and `ref_`(?). And remove `Option<..>` from `Node`'s `node_ws` and `ref_`. So Rust's type system would help to reduce errors and boiler plate in patch algorithm (`take`s and `expects`). It would be also faster because it wouldn't be necessary to check `node_ws` present in runtime.
But I don't know how much work it would mean and I'm not sure if it wouldn't make code less readable / create some ergonomics problems.

_Originally posted by @MartinKavik in https://github.com/David-OConnor/seed/pull/174_

**Comment by MartinKavik** [comment]
https://github.com/David-OConnor/seed/pull/174#discussion_r301123630

**Comment by David-OConnor** [comment]
Leaning wrapper struct containing fields for the vdom `Node` and `web_sys::Node`. Removing `node_ws` from `El` and `Text`.

**Comment by bgourlie** [comment]
Out of curiosity, and with respect for the fact that it is entirely non-trivial, how feasible would using something like dodrio for the virtual DOM be?

**Comment by David-OConnor** [comment]
Unfeasible. It takes a different approach to state management.

**Comment by MartinKavik** [comment]
Closing in favor of https://github.com/David-OConnor/seed/issues/138.
