### ISSUE TITLE
Question: Is "--target no-modules" required when building?

### ISSUE THREAD

**Issue by bgourlie** [David-OConnor/seed#181]
I noticed that all the build targets use `wasm-pack build --target no-modules ...`.

Is `--target no-modules` required? It prevents me from calling external js functions from within my app.

Thanks!

Brian

**Comment by MartinKavik** [comment]
@bgourlie Could you test it with [branch](https://github.com/MartinKavik/seed/tree/wasmpack_target_web) in related PR? (`web` instead of `no-modules`)

**Comment by bgourlie** [comment]
I modified my current project according to the changes in your branch, and it worked!

**Comment by MartinKavik** [comment]
@bgourlie Can we close it?

**Comment by bgourlie** [comment]
Yep!
