### ISSUE TITLE
add suuport for conditional attributes/style

### ISSUE THREAD

**Issue by MuhannadAlrusayni** [David-OConnor/seed#182]
Hi, some time I would like to add an attribute or style when the model state changed or after an event get triggered.

It would be nice if `attrs!` and `style!` macros have the same [functionality](https://github.com/David-OConnor/seed/pull/150) in `class!` macro.

with `class!` we can do:
``` rust
class![
    "blue",
    "highlighted" => active
]
```

with `attrs!` we could have something like this:
``` rust
attrs![
    At::Required => is_required
]
```
one problem that I see with this format, is that attributes take value so maybe we cannot use this format and we may need to come up with another format.

what I'm trying to do is build reusable views using Building pattern, here is small example:
``` rust
    pub struct Input {
        name: Option<String>,
        required: bool,
        // ... the rest of input attributes
    }

    impl Input {
        pub fn name(mut self, name: String) -> Self {
            self.name = Some(name);
            self
        }

        pub fn required(mut self, required: bool) -> Self {
            self.required = required;
            self
        }

        pub fn view<Ms>(&self) -> El<Ms> {
            let mut attrs = seed::dom_types::Attrs::empty();
            if let Some(ref name) = self.name {
                attrs.add(At::Name, name);
            }
            if self.required {
                attrs.add(At::Required, "true");
            }

            input![attrs]
        }
    }
```  

this way I can use the `Input` struct like this:
``` rust
        form![
            Input::new()
                .name("username".into())
                .required(true)
                .view::<app::Msg>(),
            Input::new()
                .name("password".into())
                .required(true)
                .view::<app::Msg>(),
        ]
```

BTW thanks for making **Seed**!

**Comment by MartinKavik** [comment]
There is special handling for some attributes like `disabled` (see my recent [fix](https://github.com/David-OConnor/seed/pull/170/files)) - it basically removes given attribute from DOM when you set its value to `false`. So I think the same principle can be used for `required` (@David-OConnor ?).

Do you have some examples for `style!` macro where simple `if / else` for value isn't enough?
---

P.S. I don't fully understand why you need it in builder for creating views. I tried to write it as minimal as possible and I don't know where I would use that "better" `attrs` macro:

```rust
pub struct Input {
    attrs: seed::dom_types::Attrs,
}
impl Input {
    pub fn new() -> Self {
        Self { attrs: attrs!{} }
    }
    pub fn name(&mut self, name: impl Into<std::borrow::Cow<'static,str>>) -> &mut Self {
        self.attrs.add(At::Name, name.into().as_ref());
        self
    }
    pub fn required(&mut self) -> &mut Self {
        self.attrs.add(At::Required, "true");
        self
    }
    pub fn view<Ms>(&self) -> El<Ms> {
        input![&self.attrs]
    }
}
```
```rust
Input::new()
    .name("username")
    .required()
    .view()
```

**Comment by MuhannadAlrusayni** [comment]
> There is special handling for some attributes like disabled (see my recent fix) - it basically removes given attribute from DOM when you set its value to false. So I think the same principle can be used for required (@David-OConnor ?).

There's a few other attributes that's similar to disabled (e.g. checked, multiple, readonly, .etc) not sure if they need to be handled like the way seed handle disabled attribute.

I think this need it's own issue.

> Do you have some examples for style! macro where simple if / else for value isn't enough?

I don't have any use case for `style!` macro yet.

> P.S. I don't fully understand why you need it in builder for creating views. I tried to write it as minimal as possible and I don't know where I would use that "better" attrs macro:

I think my short example doesn't show a good reason for using builder pattern. here is one function that I use to have reusable view:
``` rust
// more arguments maybe added in future if needed
pub fn input(
    name: &str,
    required: bool,
    input_type: Option<&str>,
    placeholder: Option<&str>,
    max: Option<isize>,
    mid: Option<isize>,
    size: Option<isize>,
    input_handler: Option<impl FnMut(String) -> app::Msg + 'static>,
) -> El<app::Msg> {
    unimplemented!()
}
```
As you can see, this function have a lot of optional arguments, and using it isn't as nice as Builder structs:
``` rust

pub fn view(model: &Model) -> El<Msg> {
    form![
        input(
            "username",
            true,
            None,
            Some("sami"),
            None,
            None,
            None,
            move |v| { Msg::UpdateUsername(v) }
        ),
        input(
            "password",
            true,
            Some("password"),
            None,
            None,
            None,
            None,
            move |v| { Msg::UpdatePassowrd(v) }
        ),
        input(
            "email",
            true,
            Some("email"),
            Some("email@example.com"),
            None,
            None,
            None,
            move |v| { Msg::UpdateUsername(v) }
        ),
        input(
            "phone",
            false,
            Some("tel"),
            Some("0512345678"),
            None,
            None,
            None,
            move |v| { Msg::UpdateUsername(v) }
        ),
        // the rest of the form input
    ]
}
```
with builder struct, this would be shorter and more readable:

``` rust

pub fn view(model: &Model) -> El<Msg> {
    form![
        Input::text()
            .name("username")
            .required()
            .placeholder("sami")
            .input_ev(Msg::UpdateUsername)
            .view(),
        Input::password()
            .name("password")
            .required()
            .input_ev(Msg::UpdatePassowrd)
            .view(),
        Input::email()
            .name("email")
            .required()
            .placeholder("email@example.com")
            .input_ev(Msg::UpdateEmail)
            .view(),
        Input::tel()
            .name("phone")
            .placeholder("0512345678")
            .input_ev(Msg::UpdatePhone)
            .view(),
        // the rest of the form inputs
    ]
}
```
Also with builder struct we can force HTML rules in the type system, something like this:
``` rust
pub struct Input {
    // omited
}

impl Input {
    pub fn text() -> TextInput {
        unimplemented!()
    }

    pub fn button() -> ButtonInput {
        unimplemented!()
    }

    // ..
}

pub struct TextInput {
    // omited
}

impl TextInput {
    pub fn view<Ms>(&self) -> El<Ms> {
        unimplemented!()
    }

    pub fn placeholder(mut self, v: &str) -> Self {
        unimplemented!()
    }

    pub fn value(mut self, v: &str) -> Self {
        unimplemented!()
    }

    // ..
}

pub struct ButtonInput {
    // omited
}

// placeholder attr doesn't apply for button so ButtonInput doesn't provide
// function for it
impl ButtonInput {
    pub fn view<Ms>(&self) -> El<Ms> {
        unimplemented!()
    }

    pub fn value(mut self, v: &str) -> Self {
        unimplemented!()
    }

    // ..
}
```
We can also force our own rules using builder structs.

**Comment by David-OConnor** [comment]
`checked` has special handling. Sounds like I need to add some for `readonly` and `multiple`.

**Comment by David-OConnor** [comment]
Re the original issue: We could handle it by adding a dummy val that tells the `vdom` (via the attribute shim) not to add that attribute at all. (ie as `disabled` does currently). Assuming I've understood correctly.

**Comment by MartinKavik** [comment]
> We could handle it by adding a dummy val that tells the render code (via the attribute shim) not to add that attribute at all. (ie as At::Disabled always does).

What about to remove special handling / the most of shims and make it more explicit / simple?
Examples:

- `input![ attrs!{ At::Required => true } ]`  -->  `<input required="true">`
- `input![ attrs!{ At::Required => () } ]`  -->  `<input required>`
- `input![ attrs!{ At::Required => Some(true)} ]`  -->  `<input required="true">`
- `input![ attrs!{ At::Required => Some(()} ]`  -->  `<input required>`
- `input![ attrs!{ At::Required => None } ]`  -->  `<input>`

(Same for `style!, except `()` - because I think it doesn't make sense to have style property without value)

**Comment by MuhannadAlrusayni** [comment]
Both solutions works for me.

**Comment by MartinKavik** [comment]
I'll try to implement it like I suggested in my previous comment.
@David-OConnor Do you agree?

**Comment by David-OConnor** [comment]
Yep. Should make this part of the API more consistent, at the cost of being breaking.

**Comment by MuhannadAlrusayni** [comment]
Thanks for the quick fix.  Should I close this ?

**Comment by MartinKavik** [comment]
Yeah
