### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by jgrund** [David-OConnor/seed#190]
Hi, 

Just wondering if there is a timetable for releasing 0.4.

There are a number of useful changes that we'd like to integrate with

**Comment by David-OConnor** [comment]
I was waiting until fixing a markdown/raw-html bug that's been hard to track down. Will take a look this weekend

**Comment by David-OConnor** [comment]
I think the markdown bug may be a bug in the markdown I was using vice the renderer. Released.

**Comment by jgrund** [comment]
Thanks @David-OConnor
