### ISSUE TITLE
RealWorld example and awesome list

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#191]
Just a small announcement of two new projects related to Seed:

- "The mother of all demo apps" — Exemplary fullstack Medium.com clone in Seed
  - https://github.com/MartinKavik/seed-rs-realworld
  - routing, tests, sub-modules, local storage, requests with error handling, travis + netlify, ...
  - based on default quickstart => no javascript
  - 5k LoC

- A curated list of awesome things related to Seed
  - https://github.com/MartinKavik/awesome-seed-rs

Feedback, new issues / PRs are very welcome. Thanks!

---

P.S. Quickstart with webpack updated and refactored a little bit.
  - https://github.com/MartinKavik/seed-quickstart-webpack/blob/master/CHANGELOG.md

**Comment by David-OConnor** [comment]
Outstanding

**Comment by TatriX** [comment]
As I can see realworld demo is using non-master branch. Can you please explain why it's the  case?

**Comment by MartinKavik** [comment]
@TatriX I just forgot to switch it after that branch has been merged into master. I've fixed it and it's already redeployed and everything seems to work without code changes. Good question.

**Comment by MartinKavik** [comment]
**Update**: I've added book `Engineering Rust Web Applications` and `kavik.cz` into awesome list.
 - Book looks interesting, I look forward to new chapters. 
 - Kavik.cz is my new website - it's written in Seed, but more interesting fact is: It's prerendered before deploy. So we are able to create landing pages, documentations and other sites with super fast first render and good SEO now.

@David-OConnor Yeah, I'm biased here but I think it would be nice to have a link to awesome list in Seed's readme or homepage.

**Comment by David-OConnor** [comment]
Added Awesome List and Seed Realworld to the website; will be in next Readme commit.
