### ISSUE TITLE
Help Needed with Fetch with header

### ISSUE THREAD

**Issue by TuntematonSotilas** [David-OConnor/seed#192]
Hello , I need help with the Request method : 
I try to get some datas from my backend wich needs a special header named "token"

So I do this : 
```Rust
Request::new(api_url.clone())
        .header("token", &token) 
        .fetch_json(Msg::DataFetched)
```
But I dont see my header "token" in the Request Headers in chrome debugger , and nor in my backend in debug mode.

FYI : I use seed version 0.4

Tanks for your help

**Comment by David-OConnor** [comment]
Unsure if this is a bug or something else yet. Will get back to you. Does it seem to only happen with the "token" header, or others as well?

**Comment by TuntematonSotilas** [comment]
It works with a POST request : i see my "token" header 
I seems I have a CORS problem on my GET so thats why I don't see the header, 
I'll try to fix this CORS error and it will be OK I think
