### ISSUE TITLE
Question: inconsistent behavior in rendering and lifecycle hooks

### ISSUE THREAD

**Issue by wayeast** [David-OConnor/seed#200]
I do not know if this is an issue with seed or with my usage of it, but there are two patterns of behavior that are puzzling me.  One is with rendering, which may or may not be triggered after a model update; another is with lifecycle hooks, which seem to require different conditions to fire.

I have created a small toy example [here](https://gist.github.com/wayeast/59b510f5163ca78273c413c34d9b2b12) that reproduces the issues I'm running into in my project.  This code can be dropped into the seed quickstart repo and run as is.  I've added comment blocks to point out where the problems occur and my puzzlement over them, but they are essentially this:

1) DOM rendering does not appear to be triggered after some updates.  In my example, I don't understand why the [update](https://gist.github.com/wayeast/59b510f5163ca78273c413c34d9b2b12#file-lib-rs-L100) highlighted is not rendered while updates that follow the same pattern a few lines [above](https://gist.github.com/wayeast/59b510f5163ca78273c413c34d9b2b12#file-lib-rs-L84-L85) are.
2) A lifecycle hook in a simple div [here](https://gist.github.com/wayeast/59b510f5163ca78273c413c34d9b2b12#file-lib-rs-L120) is fired just fine, while [another](https://gist.github.com/wayeast/59b510f5163ca78273c413c34d9b2b12#file-lib-rs-L152) requires an extra div wrapper to fire.  If I repeat the same pattern from a few lines above, the latter closure will not fire!

Any help to understand what's going on and how to work with these patterns would be appreciated.

**Comment by MartinKavik** [comment]
The root of all evil is `did_mount`. We are discussing hooks here: https://github.com/David-OConnor/seed/issues/82. They don't work reliable (and probably somehow break render loop in your example) and in the most cases it's an anti-pattern to use them. 

I've refactored your example: https://gist.github.com/MartinKavik/c8ef497a26c6506d2b1f5615397f5b45 (see comment). 

P.S. If you want some inspiration for auth and login form, you can look at https://github.com/MartinKavik/seed-rs-realworld.

**Comment by rebo** [comment]
Also having some issues with did_mount, sometimes they fire and sometimes not.

However I need something to fire so I can trigger re-rendering of MathJax.

**Comment by MartinKavik** [comment]
@rebo Could you send link to the minimal example with your use-case of `did_mount`  to https://github.com/David-OConnor/seed/issues/82? So we can fix and design better hooks (or remove them).

**Comment by rebo** [comment]
Hi Yes sure, i also have another issue i need to make a minimal example of. Will endeavour to get both done this evening.

**Comment by rebo** [comment]
This gist seems to exhibit the issue:

https://gist.github.com/rebo/d9a1c6314ce1726e77b74708afd87d4d

Sorry it is fairly long however i had to incorporate much of the Node structure in my original app in order to trigger the problem. The app requires tailwindcss as well as fontawesome to properly render.

I think it is something to do with the structure of the Nodes generate in the ::detail_pane function:

```rust
pub fn detail_pane(entity: &Thing, model: &Model) -> Node<Msg> {
    if model.edit_detail_pane.is_some() {
        modal_confirm_cancel_dialog(
            entity.name.clone(),
            div![form(&entity, FormType::Update)],
            "Update".to_string(),
            Msg::Update,
            "Cancel".to_string(),
            Msg::Cancel,
        )
    } else {
       modal_confirm_cancel_dialog(
            entity.name.clone(),
            div![detail(&entity)],
            "Edit".to_string(),
            Msg::Edit,
            "Close".to_string(),
            Msg::Cancel,
        )
    }
}
```
The first time a user triggers this function it goes down the None path and shows a modal detail pane. The node structure for this is generated by ::modal_confirm_cancel_dialog which takes ::detail(&entity) as an argument.

When the user clicks edit, the ::detail_pane takes the Some path and renders a form.

I think when rendering the Some path (rendering ::form)  it clashes with the hooks in ::detail. and the hook inside ::form is never triggered.

Strangely enough if I change the div![detail(&entity)] in the above function to p![detail(&entity)] then the bug goes away and the hook is triggered correctly.

I need most of the above hooks as they re-render mathjax on view update.

**Comment by MartinKavik** [comment]
@rebo 
I suggest to delete all hooks and replace them with custom elements - I've refactored Seed's `mathjax` example to use custom element (https://github.com/David-OConnor/seed/pull/202) for inspiration.
After that your Rust code with business logic should be shorter & easier to reason about (especially `fn detail`). 
Do you think there is a case in your code where you have to use hooks and there is no other option?

---

> In the mean time I am having more success using Orders and perform_cmd than the lifetime hooks

Nice!

---

Note: You are using Tailwind => look at https://github.com/MartinKavik/seed-quickstart-webpack.

**Comment by rebo** [comment]
Thanks for the advice regarding the custom elements I will look at that now.

And yep I'm using your seed-quickstart-webpack with yarn etc. Its great!

**Comment by wayeast** [comment]
@MartinKavik thanks for the refactored code.  I have been able to go back through my project and make changes in accordance with you suggestions.  The problems I mentioned on opening this thread (appear to) have been solved.

**Comment by MartinKavik** [comment]
> One area that I am using did_mount is for input focusing. If these hooks were removed how would this use case be handled? (maybe by an Order command again?)

1. You can use attribute `autofocus` - see a month old [change]( https://github.com/David-OConnor/seed/blob/master/src/websys_bridge.rs#L196) in Seed core.
Example:
```rust
input![
    attrs! { At::AutoFocus => AtValue::None }
]
```
2. Or set it manually (as you probably suggested with Orders) when do you want with the code like the one in the core.

If none of these options are applicable for you, just create a small example and we will find another solution.

**Comment by MartinKavik** [comment]
FYI:
> One area that I am using did_mount is for input focusing. If these hooks were removed how would this use case be handled? (maybe by an Order command again?)

There is a new API which you can use -  see `canvas` example - https://github.com/David-OConnor/seed/blob/a3dfe6cbf4f165c195fd2b130db059094761cf04/examples/canvas/src/lib.rs#L44

---

Original issues should be resolved, I suggest to close it.
