### ISSUE TITLE
Help needed for file upload

### ISSUE THREAD

**Issue by TuntematonSotilas** [David-OConnor/seed#205]
I have created an input of type file :
```RUST
input![
	attrs!{
		At::Type => "file",
		At::Accept => "image/png, image/jpeg",
		At::Multiple => true
	},
	raw_ev(Ev::Input, Msg::SendFiles)
]
```
And then I'm stuck with parsing the message :
```RUST
Msg::SendFiles(event) => {
```
How the parse the datas to get the blobs ?

Tanks for your help

**Comment by MartinKavik** [comment]
Look at the `server_integration` example for some inspiration - https://github.com/David-OConnor/seed/blob/master/examples/server_integration/client/src/example_e.rs#L191.

**Comment by TuntematonSotilas** [comment]
Thanks a lot, it will be a great help
