### ISSUE TITLE
Drop File Event

### ISSUE THREAD

**Issue by TuntematonSotilas** [David-OConnor/seed#229]
Hello , 

I woould like to implement a Drop File like this example (JS): 
https://www.html5rocks.com/en/tutorials/file/dndfiles/

So I did that : 
```RUST
raw_ev(Ev::DragOver, |event| {
	event.stop_propagation();
	event.prevent_default();
	//event.data_transfer().dropEffect = 'copy';
	Msg::DropFile
}),
raw_ev(Ev::Drop, |event| {
        //let files = event.data_transfer().files();
	Msg::DropFile
}),
```

But I'm stuck with
parsing `web_sys::Event` to  `web_sys::DragEvent` 
beceause I need the method data_transfer which is only in DragEvent

Thanks for your help

**Comment by MartinKavik** [comment]
Hi. See https://github.com/David-OConnor/seed/pull/230/files  (related PR)

**Comment by David-OConnor** [comment]
Love it!

**Comment by TuntematonSotilas** [comment]
Thanks a lot
