### ISSUE TITLE
Ask: How to use promise

### ISSUE THREAD

**Issue by daogangtang** [David-OConnor/seed#237]
Hi, If I want to use the API: "get_user_media", I find it returning a promise, 

```
pub fn get_user_media_with_constraints(
    &self, 
    constraints: &MediaStreamConstraints
) -> Result<Promise, JsValue>
```

How to use it? Do I need to use futures to handle it, like the FetchObject?

Thank you.

**Comment by MartinKavik** [comment]
Hi. See related PR https://github.com/David-OConnor/seed/pull/238 for an example.

**Comment by daogangtang** [comment]
:+1:

**Comment by MartinKavik** [comment]
I think we can close it.
