### ISSUE TITLE
How to get a exists element?

### ISSUE THREAD

**Issue by lalalili18999** [David-OConnor/seed#24]
for example: 
first question: 
I want to change the window title like this: 
`window.title = "new title";`
and how to do it via seed ?

second question:
i created a node: input ![..] and append a node: em! [..]
if user typed illegal letters, the node em![] change its text color to warn user: you are wrong..
how to do it via seed? 

thank you very much. u r a nice person!

**Comment by David-OConnor** [comment]
First:
Add this to your top-level element:
```rust
        did_mount(|_| {
            web_sys::window().unwrap().document().unwrap()
                .set_title("new title")
        })
```
In the next release this will be simplified to:
```rust
did_mount(|_| { seed.document().set_title("new title")  })
```

Second: I'm not sure how you'd put an em! in an input, but I think you're looking for something like this:
```rust
fn view(state: seed::App<Msg, Model>, model: Model) -> El<Msg> {
    let illegal_chars = ["D", "R", "U", "G", "S"];
    let mut valid = true;
    for illegal in &illegal_chars {
        if model.text.contains(illegal) {
            valid = false
        }
    }
    input![
        style!{"color" => if valid {"green"} else {"red"}; "font-weight" => "bold"},
        input_ev("input", Msg::ChangeText)
    ]
}
```
