### ISSUE TITLE
Not finding app element on lastest Safari 13.0.2 

### ISSUE THREAD

**Issue by tiberiusferreira** [David-OConnor/seed#241]
After cloning https://github.com/David-OConnor/seed-quickstart.git and doing:
cargo make build
and
cargo make serve , console shows:

```
panicked at 'Can't find element with id="app" - app cannot be mounted!
(Id defaults to "app", or can be set with the .mount() method)', /Users/tiberiodarferreira/.cargo/registry/src/github.com-1ecc6299db9ec823/seed-0.4.1/src/vdom.rs:145:13
```

I changed the render function to: 
```

#[wasm_bindgen(start)]
pub fn render() {
    let el = web_sys::window().unwrap().document().unwrap().get_element_by_id("app").unwrap();
    log!(el);
    seed::App::build(init, update, view)
        .finish()
        .run();
}
```
and it does log the element, so it exists and the bindgen functions are working. I'm not sure what's going on. https://seed-rs.org does render correctly.

**Comment by David-OConnor** [comment]
Can you post the HTML file?

**Comment by tiberiusferreira** [comment]
It's the default one:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="">

    <link rel="icon" type="image/png" href="/public/favicon.png">

    <title>A Title</title>

    </head>

    <body>
        <section id="app"></section>
        <script type="module">
            // https://rustwasm.github.io/docs/wasm-bindgen/examples/without-a-bundler.html
            import init from '/pkg/package.js';
            init('/pkg/package_bg.wasm');
        </script>

    </body>
</html>
```

**Comment by David-OConnor** [comment]
Is it working in Chrome and Firefox?

**Comment by tiberiusferreira** [comment]
Yes, it does work on Chrome 77 and Firefox 70.0b13

**Comment by MartinKavik** [comment]
@David-OConnor Do you have Safari? I have macOS in wmvare/virtualbox + Safari on iOS, I think I can try to debug it.

**Comment by David-OConnor** [comment]
Don't have Safari; would appreciate that.

**Comment by MartinKavik** [comment]
So...

I see the same error on:
- Safari 12.1.2 on macOS 10.14.6
- Chrome, Firefox, Safari on iOS 13.1.2

Workaround:
```rust
#[wasm_bindgen(start)]
pub fn start() {
    log!("Seed started.");   //  <-- this

    seed::App::build(|_, _| Init::new(Model::default()), update, view)
        .finish()
        .run();
}
```
Yes, it looks like basically everything which communicates directly with browser somehow resets/warms it up and then it works.
Another example:
```rust
#[wasm_bindgen(start)]
pub fn start() {
    log!(seed::document().get_element_by_id("app")); // ->  None
    log!(seed::document().get_element_by_id("app")); // -> Some(..)

    seed::App::build(|_, _| Init::new(Model::default()), update, view)
        .finish()
        .run();
}
```
Safari and all iOS browsers (because of Apple) uses Webkit (if I'm not wrong). So it looks like a Webkit bug.

@tiberiusferreira:
   1. Does a workaround, like the ones above, help with your problem with Safari?
   1. Desktop Safari - I see two errors in console:
        1. The one you described in the previous comment.
        1. `Unhandled  Promise Rejection: Error: Unreachable code should not be executed ...` - do you see it too?

There are some similar errors (like the second one) in this list: https://bugs.webkit.org/buglist.cgi?component=WebAssembly&product=WebKit&resolution=---

**Comment by tiberiusferreira** [comment]
Thank you very much for the investigation and workaround. Yes, this workaround can work for me. I'll try it when I get home.

**Comment by tiberiusferreira** [comment]
Yes, I see two errors: 

<img width="1440" alt="Screen Shot 2019-10-12 at 14 44 54" src="https://user-images.githubusercontent.com/5420615/66705574-e6d3cf80-ecfe-11e9-8774-a1ece8cb7317.png">

Adding 

```
    log!("Seed started.");
``` 
Resulting in: 
```
#[wasm_bindgen(start)]
pub fn render() {
    log!("Seed started.");
    seed::App::build(init, update, view)
        .finish()
        .run();
}
```
Works like charm. Thanks. 

Maybe we should document it somewhere for newcomers until this is fixed by Apple.

**Comment by MartinKavik** [comment]
> Maybe we should document it somewhere for newcomers until this is fixed by Apple. Should I close this or keep it open as a reminder to see if Apple fixed it in the future?

I suggest to add a dummy call like `log!("Seed started.");` or something less visible directly into Seed with `todo` line. Even if Apple fix it, we still need to support older browsers for a while.
And close this issue because it can scare new Seed users.
@David-OConnor ?

**Comment by MartinKavik** [comment]
@tiberiusferreira Can I ask you a favor? Could you please report our findings to the existing / new issue on that list (https://bugs.webkit.org/buglist.cgi?component=WebAssembly&product=WebKit&resolution=---)? You have more experience with macOS and real HW. Thank you!

**Comment by tiberiusferreira** [comment]
Sure, created it here: https://bugs.webkit.org/show_bug.cgi?id=202881

**Comment by David-OConnor** [comment]
> > Maybe we should document it somewhere for newcomers until this is fixed by Apple. Should I close this or keep it open as a reminder to see if Apple fixed it in the future?
> 
> I suggest to add a dummy call like `log!("Seed started.");` or something less visible directly into Seed with `todo` line. Even if Apple fix it, we still need to support older browsers for a while.
> And close this issue because it can scare new Seed users.
> @David-OConnor ?

I like it. Would rather make this *just work* than require additional code from the user.
