### ISSUE TITLE
Question: Is it possible to load parts of an app dynamically?

### ISSUE THREAD

**Issue by flosse** [David-OConnor/seed#246]
Let's say we're going a complex app that consist of two layers
- one layer that is for visitors
- and a additional layer for logged-in users with multiple tools

It would be cool to load the second layer only if necessary.
How would you do this?

**Comment by MartinKavik** [comment]
Some options:
1. Two standalone Seed apps.
2. Lazy-load 2nd WASM module with JS. Communication between modules through JS.
3. Lazy-load 2nd WASM module with app module. Communication between modules indirectly through JS. [Example](https://rustwasm.github.io/wasm-bindgen/examples/wasm-in-wasm.html).
4. Dynamic linking. WIP. [Docs](https://webassembly.org/docs/dynamic-linking/). A guy [tried it](https://iandouglasscott.com/2019/07/18/experimenting-with-webassembly-dynamic-linking-with-clang/) with C.

If you really need it now, I recommend to use 1 or 2. 3 is ugly and 4 is the future.

**Comment by flosse** [comment]
> If you really need it now, I recommend to use 1 or 2. 3 is ugly and 4 is the future.

Fortunately I don't need it now but I need to think about it now for the future ;-)

**Comment by flosse** [comment]
I'll close this issue because the question is answered. And hopefully I'll once contribute with a PR that shows an elegant example :)

**Comment by MartinKavik** [comment]
Just two more interesting links:
- https://github.com/web-dom/web-dom#dynamic-calls
- https://medium.com/wasmer/webassembly-sh-408b010c14db (Wasmer and similar WASM runtimes/package managers don't support dynamic linking yet but it can be a way how to split app or create plugin system in the future.)
