### ISSUE TITLE
Routes don't behave like expected

### ISSUE THREAD

**Issue by flosse** [David-OConnor/seed#247]
Using seed v0.4.1 I tried to use URL changes but it does not work:

![Bildschirmfoto_2019-10-16_21-07-47](https://user-images.githubusercontent.com/276043/66950631-08afb800-f059-11e9-99b9-72e1f84f6d5f.png)

Here is the code: https://github.com/flosse/seed/commit/5dee82944270ccda160ee574afe733bc3fd6bfb5#diff-1015f606e4bbeb299d9ce5d5d8303123

Is this a bug or a feature?

**Comment by David-OConnor** [comment]
Could you please post your `routes` function? This may be due to  mixing `hash` and `path` style routing. Note that hash routing, (ie the `#` starting your route) has generally been replaced by using straight paths.

**Comment by flosse** [comment]
> Could you please post your `routes` function? This may be due to mixing `hash` and `path` style routing.


```rust
fn routes(url: Url) -> Msg {
    Msg::Route(url)
}
```

**Comment by flosse** [comment]
I think the problem is that I'm looking for a [hashchange event](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event) that is not tracked by seed.

**Comment by MartinKavik** [comment]
@flosse A little bit OT - I haven't enountered this problem because I don't use `#`. So I'm curious - what's your use-case?

**Comment by David-OConnor** [comment]
Could you also post the code that triggers the routing? eg the update func section or listened-link.

**Comment by flosse** [comment]
> So I'm curious - what's your use-case?

We [consider to port](https://github.com/kartevonmorgen/rfcs/issues/3) the whole [kartevonmorgen](https://kartevonmorgen.org) frontend to seed.
Within the first step we want to avoid breaking changes.
So e.g. this link should show the entry with the ID `4c209..`:
https://kartevonmorgen.org/#/?entry=4c20979fe0754e74875afa4308d73ce7&zoom=15.00

**Comment by flosse** [comment]
> Could you also post the code that triggers the routing? eg the update func section or listened-link.

As already mentioned, here is the complete example: https://github.com/flosse/seed/commit/5dee82944270ccda160ee574afe733bc3fd6bfb5#diff-1015f606e4bbeb299d9ce5d5d8303123

but there is no code that triggers the routing, I just change the hash within the address bar.

**Comment by David-OConnor** [comment]
The issue here is that the routing system requires something to trigger the routing; your example isn't causing the routes function to be called at all.

I'm trying to think if there's a way to make this work. Perhaps there's a way to listen for url changes like we listen for `popstate` events.

**Comment by David-OConnor** [comment]
https://github.com/David-OConnor/seed/compare/hashchange_listener?expand=1

**Comment by flosse** [comment]
> #252

thanks!
The initial state is working now :)

Changing the hash leads to the following URL:

`Url { path: ["", "localhost:8000", "#?foo=basry"], search: None, hash: None, title: None }`

**Comment by David-OConnor** [comment]
How about now?

**Comment by flosse** [comment]
> How about now?

now it's working :)

> I'm not sure how/if to handle routing being called twice.

the `popstate` gets fired first with an empty url

**Comment by David-OConnor** [comment]
Latest push should do it. Ready to merge if this is solved on your end. Popstate will no longer call the routes function if it receives a null JS value, as it does here. (Previous behavior was to call with an empty Url, as you found out.)

**Comment by AlterionX** [comment]
@flosse Was this fixed? Just pinging for a confirmation.

**Comment by MartinKavik** [comment]
@AlterionX it should be fixed - https://github.com/David-OConnor/seed/pull/252#issuecomment-544147380

**Comment by flosse** [comment]
> @flosse Was this fixed?

yes, as far as I can remember :)
