### ISSUE TITLE
idea: split seed into smaller crates

### ISSUE THREAD

**Issue by flosse** [David-OConnor/seed#248]
Currently seed has "all batteries included" that is great for a lot of use-cases but in some cases I just want to use some core functionalities.
Can we split up seed at least into two crates? e.g.
- `seed-core` - basic vdom and event handling
- `seed-batteries` - fetch, routing, storage, markdown etc.

The default `seed` crate would remain as a all-in crate.

**Comment by MartinKavik** [comment]
How did you get this idea? Do you want to use custom libs? Strip WASM size? ..

**Comment by David-OConnor** [comment]
This batteries-included approach was deliberate, with the intent of maximizing ease-of-use. If there are concrete benefits to splitting that outweigh this, like the ones Martin suggested, we'll consider.

**Comment by flosse** [comment]
> How did you get this idea? Do you want to use custom libs? Strip WASM size? ..

There are actually two reasons:
1. because I consider to use [reqwest](https://github.com/seanmonstar/reqwest)
2. because I think that the overall architecture improves if we are forced to build clean interfaces.

But for now there are probably more important things to do, so I'm totally fine to close this issue.

**Comment by David-OConnor** [comment]
You should be able to use `reqwest` without the builtin, `web_sys`-based fetch module interfering, once it fully supports wasm. Worth giving it a shot, now, or once they improve WASM functionality.

**Comment by MartinKavik** [comment]
> 1. because I consider to use reqwest

Just some info if you haven't seen it yet: https://github.com/David-OConnor/seed/issues/226.

> 2. because I think that the overall architecture improves if we are forced to build clean interfaces.

[actix -web](https://github.com/actix/actix-web) is a good example.
But I think it would slow down us now. I have bad experience from the world of microservices - if you try to split monolith into parts (i.e. define clean interfaces) before you see boundaries clearly, it turns into a mess and versioning / administration hell.
So I suggest to wait until Seed is battle-tested enough or/and adding new libraries (reqwest, gloo libs, ..) becomes too painful. And maybe it would be nice to implement this idea together with https://github.com/David-OConnor/seed/issues/246.

**Comment by flosse** [comment]
> So I suggest to wait until Seed is battle-tested enough or/and adding new libraries (reqwest, gloo libs, ..) becomes too painful. And maybe it would be nice to implement this idea together with #246.

I agree! So I'll close this issue for now.
