### ISSUE TITLE
Reserve space in `Node` for children

### ISSUE THREAD

**Issue by daxpedda** [David-OConnor/seed#262]
I'm trying to populate tables with a lot of children and thought that the ability to use `Vec::reserve` on `El::children` could be very useful in cases like these.

**Comment by MartinKavik** [comment]
Do you have an example so we can try it to see difference between both versions (with or without reserve?)

**Comment by daxpedda** [comment]
Something like this:
```rust
fn view(model: &Model) -> impl View<Event> {
    let table = table![];
    table.reserve_children(1000);

    for row_index in 0..1000 {
        let row = tr![];
        row.reserve_children(10);

        for cell_index in 0..10 {
            row.add_child(td![cell_index.to_string()]);
        }

        table.add_child(row);
    }

    return table;
}
```

I made a complete benchmark here: https://gist.github.com/daxpedda/79bdb173fad9cc2050acbd09be706304

The difference for this example on my computer is a 20 - 25% speedup.

**Comment by daxpedda** [comment]
On a sidenote, if this is too much of a niche use case, considering that all members are public an additional API is not absolutely necessary.

For example something like this can be used:
```rust
let mut table = table![];

if let Node::Element(el) = table {
	el.children.reserve_exact(1000);
}
```

**Comment by MartinKavik** [comment]
> if this is too much of a niche use case, considering that all members are public an additional API is not absolutely necessary.

I agree with this ^. If it turns out to be too painful, we can reopen this issue and design more universal API for similar cases.

**Comment by daxpedda** [comment]
Alright.
