### ISSUE TITLE
CI: Job has been terminated

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#279]
`The job exceeded the maximum time limit for jobs, and has been terminated.`
https://travis-ci.org/David-OConnor/seed/jobs/607606086

https://travis-ci.org/David-OConnor/seed/builds/607606085
Linux - 26min
Mac - killed after 50min

It's weird and I think we cannot change travis time limit per job.
Possible solutions:
1.  Restart job and hope that it was an exception.
1. Split job into more jobs.
1. Try to somehow optimize build process.
1. Migrate to other CI provider - I have better experience with Azure Pipelines. Or we can try Github Actions.

@David-OConnor Try to restart the job please, I don't have required permission.

**Comment by MartinKavik** [comment]
I have problems with travis, too:
- `Running for 11 hrs 37 min 3 sec ` - one of my Seed projects got stuck on `Compiling toml v0.5.5`..
- I had to migrate to Azure Pipeline in [MartinKavik/html-css-db](https://github.com/MartinKavik/html-css-db/blob/generator/azure-pipelines.yml), because there were some internet connection problems in travis cron.

**Comment by David-OConnor** [comment]
Working now; no idea what caused the issue before. Agree on switching if it keeps doing this. Related: I can't log into Travis on Firefox; gives me a JSON error.

**Comment by MartinKavik** [comment]
Closing, reopen when the problems appear again.
