### ISSUE TITLE
Show current version on seed-rs.org

### ISSUE THREAD

**Issue by flosse** [David-OConnor/seed#280]
I like the way rocket communicates the latest release on the main website (https://rocket.rs):

> Latest Release: 0.4.2 (Jun 28, 2019)

**Comment by David-OConnor** [comment]
Done

**Comment by MartinKavik** [comment]
@David-OConnor Could you add to RELEASE_CHECKLIST.md that we should update release version and probably changelog in seed-rs.org?

**Comment by David-OConnor** [comment]
Done and CL updated.
