### ISSUE TITLE
Enums instead of &strs for Attrs/Events/Style

### ISSUE THREAD

**Issue by David-OConnor** [David-OConnor/seed#32]
What do y'all think?

Eg instead of this:
```rust
input![ attrs!{"value" => model.what_we_count}, input_ev("input", Msg::ChangeWWC) ]
```

This:
```rust
input![ attrs!{At::Value => model.what_we_count}, input_ev(Ev::Input, Msg::ChangeWWC) ]
```
We can (and do in the case of tags and events) validate attrs/tags/events etc internally using Enums, but this might provide better real-time assessment, eg in IDEs. What do y'all think?

edit: Added this as an optional, eg the attrs! macro and event funcs accept either; leaning towards making it the default in guide/examples. Haven't done Style yet

**Comment by thedodd** [comment]
I’m a big fan of this approach. May as well leverage the type system to avoid subtle bugs in application logic.

**Comment by jesskfullwood** [comment]
Definitely in favor. We use Rust for type-safety, of course!
