### ISSUE TITLE
Trigger routing immediately upon load

### ISSUE THREAD

**Issue by flosse** [David-OConnor/seed#34]
<strike>I think in most contexts seed is used to create single page applications.
The whole app belongs to one real page but the "virtual" routing is usually done by using [`Location.hash`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/hash).
With a page located at  `https://example.com/single-page` seed should use URLs like
`single-page#home` and `single-page#other` instead of `single-page/home` and `single-page/other`.
</strike>

Make the framework trigger and update immediately upon load (see https://github.com/David-OConnor/seed/issues/34#issuecomment-458329153)

**Comment by David-OConnor** [comment]
My understanding is that # routing was a workaround used before pushState was released.

**Comment by flosse** [comment]
> My understanding is that # routing was a workaround used before pushState was released.

but if I'd copy a link like https://example.com/single-page/home and share it with someone else I'd expect that the foreign browser sends a real HTTP request to the server.

**Comment by flosse** [comment]
...e.g. try to open https://seed-rs.org/guide/12 what do you see?

**Comment by David-OConnor** [comment]
I think that's supposed to be handled on the server; I'm not sure how to do it on the hosting I'm using.

**Comment by flosse** [comment]
> I think that's supposed to be handled by the server;

to be honest, I don't want special frontend logic in my server, I just wanna drop my app on a standard server. But that's only my opinion ;-)

**Comment by David-OConnor** [comment]
Would love to see what someone more experienced with frontend routing thinks

**Comment by jesskfullwood** [comment]
Yeah you typically just get the server to serve up `index.html` on any request, then make the framework trigger and update immediately upon load. For example [here](https://github.com/rust-lang/crates.io/blob/master/src/middleware/ember_index_rewrite.rs) is there relevant `crates.io` code (crates.io is a single-page ember app).

I would recommend against using `#` for anything other than anchor tags. Routing should be done as 'natively' as possible so back, forward and linking work the same as a static site would.

**Comment by flosse** [comment]
> Yeah you typically just get the server to serve up `index.html` on any request, then make the framework trigger and update immediately upon load.

I see

> For example [here](https://github.com/rust-lang/crates.io/blob/master/src/middleware/ember_index_rewrite.rs) is there relevant `crates.io` code (crates.io is a single-page ember app).

yes, here it works as expected :)
As long as I can reproduce the route I'm totally fine with it :)

> I would recommend against using `#` for anything other than anchor tags. Routing should be done as 'natively' as possible so back, forward and linking work the same as a static site would.

Yes, in that way I can agree :)

So this issue is more about making the framework trigger routing and updating immediately upon load.

**Comment by David-OConnor** [comment]
Related: Attempting to simplify routing syntax further using Regex. (Eg set up a regex map once to match all patterns, and just have the routing events trigger pushState etc.)

**Comment by jesskfullwood** [comment]
To elaborate a little - since Seed is based on Elm - in production Elm, the `main` function is ([Browser.application](https://package.elm-lang.org/packages/elm/browser/latest/Browser#application)), which as you can see takes as the `init` argument a callback that returns `( model, Cmd msg )`. This `init`callback is called once the app has initialized, and inside that function you would typically set up the model, then parse the URL as typed into the address bar and return some kind of routing message which is then processed as part of the normal event loop.

This seems like a nice way to do it. The framework need not trigger routing itself, but merely provide the URL to some callback.

**Comment by David-OConnor** [comment]
@jesskfullwood I think creating an init argument like that's elegant. In addition to initial routing, it would remove the need to put side-effect (eg loading data from a server) setup code in a did_mount, which feels awkward.

**Comment by David-OConnor** [comment]
Is this not working for y'all? `routing::initial` gets called on app load, which checks the path against the routes HashMap. For me, it works for top-level routes, but fails on sub-routes. (Or is that my hosting and dev server?)

**Comment by David-OConnor** [comment]
I redid the routing module to use a cleaner, more flexible API, and I'm still not sure if this is a bug in seed, or a problem with server config.

**Comment by David-OConnor** [comment]
Fixed

**Comment by David-OConnor** [comment]
Fixed, by @jesskfullwood 's homepage PR reffed above
