### ISSUE TITLE
allow custom attributes

### ISSUE THREAD

**Issue by flosse** [David-OConnor/seed#35]
Using an enum for attributes is a nice idea but does not work as long you're not able to user custom ones.
E.g. here is a log of my example app that has some SVG in it:
```
Can't find this attribute: transform
Can't find this attribute: x1
Can't find this attribute: y1                                                                                                                                                   
Can't find this attribute: x2
Can't find this attribute: y2
Can't find this attribute: x1
Can't find this attribute: y1
Can't find this attribute: x2
Can't find this attribute: y2
Can't find this attribute: fill
Can't find this attribute: stroke-width
Can't find this attribute: stroke
Can't find this attribute: d
```
And I don't want to create custom attributes in another way than usual ones.

**Comment by David-OConnor** [comment]
The way to do this currently is by using At::Custom("x1") etc. It's verbose compared to the normal syntax, but given that (I suspect) custom attributes are a minority, I don't think this is excessive. What do you recommend?

**Comment by flosse** [comment]
#37 would make me happy ;-)

**Comment by flosse** [comment]
thx!
