### ISSUE TITLE
Allow deserialization error handling in fetch

### ISSUE THREAD

**Issue by glademiller** [David-OConnor/seed#36]
The Fetch module works great but it has a couple of expects where I would hope to have a Result that I can handle to say something went wrong with the request. Today you could do the string and Json deserialization manually and handle the errors but it would be nice if the built in functionality allowed for it.

**Comment by glademiller** [comment]
I totally agree. A solid solution wasn't super obvious or I would have opened a PR. Just for the sake of furthering the discussion my expectation was to be able to handle the error case and send a Msg just like I did for the success case.

**Comment by glademiller** [comment]
Looking at the discussion it seems to revolve primarily around how to handle the two different error types. For my particular use case a new error type that has From implemented for both would be enough. What other options would seem to fit the situation? If an ideal solution could be hashed out I might be able to spare some time to put up a pr.

**Comment by sapir** [comment]
Futures are now returned from `update`, and their result needs to be `Result<Msg, Msg>`, so the error case is now passed as a Msg back to the `update` function.

**Comment by David-OConnor** [comment]
@glademiller does Sapir's latest PRs/the 3.0 release resolve this?

**Comment by glademiller** [comment]
I'm assuming these are pull requests that have already been merged. If so
then no it doesn't the big issue is the two expect calls when deserializing
json and converting a string. I need to be able to handle a contract
violation by the server in a graceful way right now it would simply panic.
It does sound like the change sapir made is an improvement though. It just
doesn't solve the problem I'm seeing.

Thanks,
Glade

**Comment by MartinKavik** [comment]
I'll try to fix it.

**Comment by MartinKavik** [comment]
@glademiller Merged PR #118 should resolve your problems - could you provide feedback or/and close the issue?

**Comment by glademiller** [comment]
I haven't dug too deep but looking at the code I believe this solves the issues I had. Thank you!
