### ISSUE TITLE
Update AppBuilder mount method to accept Into<String>

### ISSUE THREAD

**Issue by jgrund** [David-OConnor/seed#40]
Please update this code:

https://github.com/David-OConnor/seed/blob/5c30b6d354b9125b26f5b2ffe1187318022e67c2/src/vdom.rs#L86-L89

So that id accepts anything that implements `Into<String>`.

That way if users want to pass in an id that is dynamic, it is reasonably possible to do so while using the builder interface.

**Comment by jgrund** [comment]
It doesn't appear there is a current work-around (without leaking memory) for this as the `vdom` module is private.

Would you take a PR for this?

**Comment by David-OConnor** [comment]
I came to the same conclusion last night. We can make VDOM public, and will take a PR
