### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by flosse** [David-OConnor/seed#42]
seed is absolutely one of my favorite rust-wasm projects at the moment.
I really would like to build a real app with it but before investing too much time into it i'd like to know your thoughts about the current state and the future of seed.
Do you see seed more as an experiment or are you planning to move it into a production ready state?

**Comment by David-OConnor** [comment]
Production ready. Unfortunately, I can't see that happening for at least another 2 months. As you can tell, we're continuing to make multiple breaking API changes, but I think it's worth it to knock these out early.

**Comment by flosse** [comment]
Thank you for that feedback, so I'll try to continue with contributions if possible :)

**Comment by David-OConnor** [comment]
I think I have the router API stabilized as of today, and hope to have the new API working and documented by this weekend. Then will tackle the out-of-order bug you noticed.
