### ISSUE TITLE
Infinite Reloads when using Query Strings 

### ISSUE THREAD

**Issue by tiberiusferreira** [David-OConnor/seed#46]
First, Thanks for this awesome project! This is my favorite Rust/Webassembly project so far. 

Adding a ?something to (any?) seed site with routing causes infinite reloads. For example: changing https://seed-rs.org/guide/7 to https://seed-rs.org/guide/7?adwd causes it to reload forever. Tested on Chrome and Safari on MacOS.

This is a problem for me because I posted my site ( https://tiberiusferreira.github.io/gringoshouse ) on facebook and facebook rewrites it as https://tiberiusferreira.github.io/gringoshouse/?fbclid=IwAR0bd0aunkNfmsimtcOvpq0VaaEbbslx_5LvqQaHRpMNbf4q2Ibs8v9may8 so I had to disable routing all together.

**Comment by David-OConnor** [comment]
Fixed, and released as 0.2.7

**Comment by tiberiusferreira** [comment]
Awesome! Thank you so much.
