### ISSUE TITLE
Component lifecycle hooks

### ISSUE THREAD

**Issue by rsaccon** [David-OConnor/seed#5]
First, this framework looks very promising and the getting-started experience was very smooth thanks to the excellent documentation! I ported an app I started with yew to seed. 

Now I would like to perform some DOM actions after a component has been inserted in the DOM, such as focus an input form element. Is this possible ?

**Comment by David-OConnor** [comment]
Something like [this in Angular](https://angular.io/guide/lifecycle-hooks)?

I was able to add a focus-selector to the counter example with the additions of the following code:

```rust
use wasm_bindgen::JsCast;   // Not required once seed::to_html_el is live

// in Msg:
    Focus(String),

// (in update):
        Msg::Focus(el_id) => {
            let document = web_sys::window().unwrap().document().unwrap();
            let input = document.get_element_by_id(&el_id).unwrap();
            let input = input.dyn_into::<web_sys::HtmlElement>().unwrap();
            // let input = seed::to_html_el(&input);
            input.focus().unwrap();
            model
        }
/// In bottom of view func:
        input![ attrs!{"id" => "A"} ],
        input![ attrs!{"id" => "B"} ],
        input![ attrs!{"id" => "C"} ],
        button![ "Focus A", simple_ev("click", Msg::Focus("A".into())) ],
        button![ "Focus B", simple_ev("click", Msg::Focus("B".into())) ],
        button![ "Focus C", simple_ev("click", Msg::Focus("C".into())) ],
```

**Comment by rsaccon** [comment]
thanks for your thoughts and the code example which illustrates how to interact with the underlying domNode.

About the life cycle hooks, I was thinking of **react** `componentDidMount`, `componentWillUnmount`, (there are more). I guess most virtual dom based frameworks have something like that. One common use case: integrating third party JS widgets.

**Comment by David-OConnor** [comment]
Adding this to the to-do list. Top priority is the Fetch API; will probably prioritize this over routing.
