### ISSUE TITLE
set_timeout is missing

### ISSUE THREAD

**Issue by johnsonw** [David-OConnor/seed#50]
The API currently wraps `set_interval` but does not provide a wrapper for `set_timeout`. Please consider adding this functionality as well.

**Comment by David-OConnor** [comment]
Added; will be in next commit and release.

**Comment by johnsonw** [comment]
Awesome, thank you for the quick response 👍

**Comment by David-OConnor** [comment]
Included in v0.2.8 release

**Comment by johnsonw** [comment]
👍
