### ISSUE TITLE
Intercept link clicks

### ISSUE THREAD

**Issue by jesskfullwood** [David-OConnor/seed#55]
A good priciple for SPAs is that navigation should work just like normal web pages. That means that links should be actual clickable links that take the user to a new URL. However, we don't actually want to force a page reload for internal links, but handle them within the app. Typically this is handled by adding a `click` handler to the link which redirects without reload, and this is possible with `seed` today. However at the moment `seed` does not intercept the default handling with `event.preventDefault()`, so in fact anchor tags with `href = ...` do still force a page reload.

[This stackoverflow answer](https://stackoverflow.com/a/33616981) has a nice JS snippet that can be added at page load which will intercept link navigation. Suggestion: `seed` should call such a function at page load. The function should also check whether the link is internal or external - if external, it should be followed normally.

**Comment by David-OConnor** [comment]
Nearly have this working. I think this could also mean normal links pointing internally could be a concise alternative to `Seed::push_path` events.

What I need to continue: What's a robust way to identify internal links? I've set it to check for the first char of the href val being '/', and I imagine we'd need to check against the hostname too. What other checks do we need to do to cover all cases?

**Comment by David-OConnor** [comment]
Working in latest commit, but only when the link starts with `/`.

**Comment by David-OConnor** [comment]
In latest release.

**Comment by David-OConnor** [comment]
Might add parsing of # and ? later.

**Comment by jesskfullwood** [comment]
You might want to look into just using [url](https://crates.io/crates/url), that's how I did it in my spin-off library. You'll want to grab the element `href` property rather than the `href` attribute - the property has been verified and canonicalized by the browser. see e.g. [here](https://github.com/jesskfullwood/tree/blob/master/src/lib.rs#L56-L58).

**Comment by David-OConnor** [comment]
Do you know of a way to access the `href` property without using `js_sys::reflect` ? Don't see it under [the HTMLAnchorElement docs](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.HtmlAnchorElement.html).

I may be underestimating subtleties of URL handling, but at a glance, the only benefit using that lib would provide is this specific case of parsing a string URL that has hash and/or search, which is easy enough to impl by splitting the string.

**Comment by jesskfullwood** [comment]
Sadly not, I filed a bug yesterday: https://github.com/rustwasm/wasm-bindgen/issues/1315

**Comment by David-OConnor** [comment]
Do all element types have this, or only anchor tags? I've taken an approach where we can add Href to any element. Not canonical HTML, but allows this routing syntax for buttons, divs etc.

**Comment by jesskfullwood** [comment]
`href` property is specific to anchor tags (and one or two other tags e.g. `<base>`). I'm a bit unclear on adding arbitrary attributes to elements. It appears to be technically invalid HTML but browsers are very permissive so probably fine in practice. Personally I would just define a click-handler on buttons etc and let the `update` function deal with routing.

Side note, you have to be careful relying on attributes, they represent the "initial" value of the element. Hit a bug recently where I set the `value` attribute of a `select` box, updated it by setting the `value` property, then fetched the `value` attribute and found it was unchanged. [Yuck!](https://stackoverflow.com/a/6004028)

**Comment by David-OConnor** [comment]
Thanks for the warning on attributes! Sounds like a trap; unknown if it could bite this approach. Based on using this shortcut API on elements other than `anchor`, I don't think we can use the `href` property. The main things I'm unsure about are if we're vulnerable to the issue you mentioned, and I have lingering doubts on the hash/search implementation. (Or if it's worth supporting them?)

**Comment by David-OConnor** [comment]
Updated hash/search to include them in the path, vice setHash and setSearch.
