### ISSUE TITLE
Useless 'unreachable executed' panic when no element with ID 'app' exists

### ISSUE THREAD

**Issue by FliegendeWurst** [David-OConnor/seed#59]
And the message in the Option::except call doesn't show up.

https://github.com/David-OConnor/seed/blob/7d5150695f790a41aef5d158f7673c9a3e3aa797/src/vdom.rs#L166-L168

**Comment by David-OConnor** [comment]
No idea on this one. Calling a panic in the match arm, when it fails, does this as well.

**Comment by jesskfullwood** [comment]
@David-OConnor Take a look at [this repo](https://github.com/rustwasm/console_error_panic_hook) for explanation

**Comment by David-OConnor** [comment]
Will be in next release
