### ISSUE TITLE
Add release mode compilation instructions to examples / readme / build scripts.

### ISSUE THREAD

**Issue by sapir** [David-OConnor/seed#68]
The `build.sh` files compile in debug mode, as do the readme instructions. `cargo build --release` greatly improves performance, but this also requires modifying the `wasm-bindgen` line, and also users might not be aware of the difference this makes.

**Comment by David-OConnor** [comment]
[In the guide](https://seed-rs.org/guide/9)

**Comment by sapir** [comment]
Ah, I didn't see that. I just based my project on the files from the quickstart :)

**Comment by David-OConnor** [comment]
Adding commented-out release commands to all example build scripts. I think this will make it more obvious/easy to switch.
