### ISSUE TITLE
Windows listeners event

### ISSUE THREAD

**Issue by frozar** [David-OConnor/seed#90]
In the example of widow listeners, if I set the `watching` field of the model to `True` by default, the listeners regarding the mouse event seem disable. It is also said at the end of [the documentation page concerning windows listeners](https://seed-rs.org/guide/3).

Do you have any clue to fix this issue? Does it come from the WASM generation or anything else?

**Comment by David-OConnor** [comment]
Bug - this is indeed the one you mentioned from the documentation. I'll take another look.

**Comment by David-OConnor** [comment]
Fixed in v0.3.1
