### ISSUE TITLE
Using Seed with Sciter

### ISSUE THREAD

**Issue by ngirard** [David-OConnor/seed#94]
Is it possible to use Seed to develop applications with [Sciter](https://github.com/sciter-sdk/rust-sciter) for front-end ?

**Comment by David-OConnor** [comment]
I can't comment decisively, as I haven't used Sciter. From the Readme and examples, it appears that it uses its own rendering engine, vice the DOM. There are currently no plans to make Seed support non-DOM backends, so I don't think it's possible. Let me know if I've misunderstood Sciter.
