### ISSUE TITLE
Seed logo

### ISSUE THREAD

**Issue by MartinKavik** [David-OConnor/seed#98]
I've got a creative moment, so I tried to design a Seed logo:

## Industrial

<p align="center">
  <img src="https://raw.githubusercontent.com/MartinKavik/seed/feat/logo-industrial/seed_branding/seed_logo.svg?sanitize=true" width="256" title="Seed logo">
</p>

- See it in readme: https://github.com/MartinKavik/seed/tree/feat/logo-industrial
- Notes:
  - Inspired by Rust logo
  - You can see a wrench in 'e' (Seed is a _tool_ for creating apps)
  -  'S' can be used standalone (e.g. in favicon)

## Natural

<p align="center">
  <img src="https://raw.githubusercontent.com/MartinKavik/seed/feat/logo-natural/seed_branding/seed_logo.svg?sanitize=true" width="256" title="Seed logo">
</p>

- See it in readme: https://github.com/MartinKavik/seed/tree/feat/logo-natural
- Notes:
  - A little bit Inspired by Rust logo and a conker seed
  -  'S' can be used standalone (e.g. in favicon)

**Comment by David-OConnor** [comment]
Love it: Both the design itself, and your reasoning behind it. 

I'm not sure which I like more overall - the Industrial design is cleaner, but the Natural one fits more with the organic nature of seeds. How about this: PR whichever readme you prefer, and I'll merge it.
